### ISSUE TITLE
compile forces .sln save

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#473] opened 2018-11-20 10:59 UTC
since I updated to the latest version (skipping ~ 2 month time), I get my .sln file force-saved as I invoke clang compoile.

My projects include a machine-local .props and it has some project renaming like:

  <PropertyGroup Condition="'$(ProjectName)'=='fem'">
    <ProjectName>0 fem</ProjectName>
  </PropertyGroup>

this works fine and is needed to make the projects appear in prop[er order in the solution explorer. 
This causes the following change in the .sln:

-Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "fem", "fem.vcxproj", "{2C5475D2-ED0E-439B-9E19-FF085365FAE3}"
+Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "0 fem", "fem.vcxproj", "{2C5475D2-ED0E-439B-9E19-FF085365FAE3}"

In normal VS work the sln is not marked dirty internally, only actual change like add/remove project forces a save. But current CPT does something along those lines.

The effect is more than annoying, as the .sln file is obviously under git and creates a delta, it must be reset before any operation or risk getting committed with changes.  Ignore does not work on contained files....

Please locate the change that caused this and at least allow to turn it off.

**Comment by Enache-Ionut** [comment] 2018-12-10 10:23
Hi,

This issue was fixed and it will be available in the next Clang Power Tools version.

Thank you for your feedback!

**Comment by pasa-** [comment] 2019-01-28 16:26
as of today, ver 4.6 still has this problem.  I could not locate a related commit to tell whether "next" might mean a later update.  If the fix is supposedly deployed, please repoen the issue.

**Comment by Enache-Ionut** [comment] 2019-02-15 08:11
Hi,

I made a fix which will be available in the next Clang Power Tools version (v4.8).
After you install the latest build coming out very soon could you please confirm the issue was solved and close it.

I will let you know when the CPT v4.8 will be online.

Best regards,
Ionut

**Comment by Enache-Ionut** [comment] 2019-02-19 08:01
Clang Power Tools v4.8 is now online. Please let me know if the issue is still there.

**Closed** 2019-02-19 09:18 UTC
Labels: bug

**Comment by pasa-** [comment] 2019-03-06 12:26
Looks fixed now! :)
