### ISSUE TITLE
<CompileAs>CompileAsCpp still ignored from .props

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#377] opened 2018-07-05 10:04 UTC
#358 was recently closed, but 3.7.1 still has the issue if configured through props. See attached project still does c type compile in clang unless I apply the workaround mentioned there.

While at it you may check if the precompiled header works as you intended, to me the output suggests it is not the same as msvc uses, just picks the first, not both.

also, I keep getting on (just) one of my machines:
At C:\Users\Baloghp\AppData\Local\Microsoft\VisualStudio\15.0_25367ff3\Extensio
ns\fqpu3bzr.rvz\psClang\msbuild-project-load.ps1:35 char:5
+     Set-Variable -name $name -Value $value -Scope Global
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (HOME:String) [Set-Variable], Sessio 
   nStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotWritable,Microsoft.PowerShell.Command 
   s.SetVariableCommand

and have to patch the location after every update with 

    Set-Variable -name $name -Value $value -Scope Global  -ErrorAction SilentlyContinue

I think that could be there without any harm

[cpt2.zip](https://github.com/Caphyon/clang-power-tools/files/2166087/cpt2.zip)

**Comment by hero101111** [comment] 2018-07-06 09:57
Hello,

Apologies for not getting your issue fixed with the latest CPT release.
Looks like there's been a misunderstanding on our part regarding the `<CompileAs>` project setting.

We've set up _clangpowertools_ to skip PCH creation for `CompileAs=CompileAsC` as we came to believe this was the issue: Projects marked with `CompileAsC` that were compiled with `clangpowertools` crashing the build.
From your recently uploaded sample project, we've seen that you've set `CompileAs` to `CompileAsCpp`. 

For this scenario we have _not_ changed CPT's behavior. This is not related to having the setting located in a property sheet. That is fully functional. 

Please go into detail on how `CompileAsCpp` affects your project compilation, when it contains `.C` files.

-----------------
> While at it you may check if the precompiled header works as you intended, to me the output suggests it is not the same as msvc uses, just picks the first, not both.

I'm afraid I don't understand what you mean by this. Please elaborate.

----------------

Regarding `Set-Variable -name $name -Value $value -Scope Global  -ErrorAction SilentlyContinue`:
This most definitely should _not_ be done. That code lies inside a heavily used utility function. 
Silent errors in these places are not something anyone would want. 

The fact that you got an error is a _good_ thing. We now know there's an issue and we can further investigate. What you should do is activate CPT **verbose mode** and give us the build log. 

The verbose log should help us pinpoint the exact property that's problematic on your build machine. 
Based on that information we'll see what can be done.


Regards,
Gabriel

**Comment by pasa-** [comment] 2018-07-06 12:42
I described (my) main problem in #358 that was in essence ignoring the CompileAsCpp setting completely and run clang in "C" compile mode based just on file extension matching ".c". From the issue being closed and listed in fix I assumed without check that the project attached to that issue now works fine :).    The .pch note in the title was just collateral damage from the C++-made pch was used with the .c in wrong mode.      A core fix should skip the extension check if CompileAs is in effect.

For the 3rd issue the relevant part of the log is in the first post, just somewhat ruied by the autoformatter: when you iterate the environment variables it chokes on HOME that is considered read-only on this machine (no idea why, might be from Win7 Enterprise, from being in domain,  some group policy entry).  It works fine on my other installations.   I actually agree that silencing set-var is gross, however just the foreach ($var in (Get-ChildItem Env:))    {      Set-Var -name $var.Name -value $var.Value      } loop could be silenced with less risk... probably.

As for the second point, build the attached project in VS: you see the 2 header messages in pch.cpp and none for the 2 files.  With clang I see the first in pch and the other with the individual files.  As you seem to build the pch not from the TU marked for that (pch.cpp for me that is an empty file) but just pass the FIRST forced header directly. If there are reasons to base pch on the forced includes, then you should pass the LAST forced header as the TU and the others as forced include option.

**Comment by hero101111** [comment] 2019-03-07 22:45
Hello,

The error related to systems that have the `HOME` environment variable set has been fixed as part of the `v4.9` release of Clang Power Tools.

The `CompileAsCpp` issue is due to be fixed in the next release (`v5.0`). We'll update this thread as soon as progress is made.

Regards,
Gabriel

**Comment by hero101111** [comment] 2019-03-11 08:44
Hi again,

Glad to inform you that we've just pushed a fix for the `CompileAsCpp` project issue as well. It will be available in the next release of Clang Power Tools (`v5.0`).

Thank you for your feedback and understanding.

Regards,
Gabriel.

**Closed by hero101111** 2019-03-11 08:44 UTC
Labels: bug

**Comment by hero101111** [comment] 2019-03-25 09:25
Hello again,

A quick update: We've had a bit of rescheduling of the release schedule and version `v4.10` was released a few days ago, instead of `v5.0`. Nonetheless, the fix _is_ included in `v4.10`.

Regards,
Gabriel.

**Comment by pasa-** [comment] 2019-03-25 15:00
The CompileAs now seems to work fine.

 

However lot of other things broke: 

*	“Compile” used to work on active file in the editor, now always uses the current selection in the Solution explorer (even if it is closed)
*	compile fails in mfc headers, in very weird way:

 

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afx.h:329:

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atltrace.h:17:

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atlconv.h:27:

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atlalloc.h:18:

In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um/ole2.h:37:

In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objbase.h:27:

In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\combaseapi.h:363:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6184): error: C++ requires a type specifier for all declarations

            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) BYTE *buf,

… and ton of other errors, the __RPC SAL macros do not get defined sensibly. I tried to include <rpcsal.h> and define _SAL1_2_Source_, that does nothing.   Only #define all the __RPC macros makes it past.  With that more weird errors:
 

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afxwin.h:2117:

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include/afxrendertarget.h:23:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\d2d1.h(820): error: use of undeclared identifier 'D3D_FEATURE_LEVEL_9_1'; did you mean 'D3D10_FEATURE_LEVEL_10_1'?

    D2D1_FEATURE_LEVEL_9 = D3D_FEATURE_LEVEL_9_1,

                           ^

C:\Program Files (x86)\Microsoft DirectX SDK (November 2008)\Include\d3d10_1.h(133): message: 'D3D10_FEATURE_LEVEL_10_1' declared here

        D3D10_FEATURE_LEVEL_10_1        = 0xa100

        ^

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afxwin.h:2117:

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include/afxrendertarget.h:26:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wincodec.h(8160): error: unknown type name 'DXGI_JPEG_AC_HUFFMAN_TABLE'

            /* [out] */ __RPC__out DXGI_JPEG_AC_HUFFMAN_TABLE *pAcHuffmanTable) = 0;

                                   ^

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wincodec.h(8165): error: unknown type name 'DXGI_JPEG_DC_HUFFMAN_TABLE'

            /* [out] */ __RPC__out DXGI_JPEG_DC_HUFFMAN_TABLE *pDcHuffmanTable) = 0;

                                   ^

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wincodec.h(8170): error: unknown type name 'DXGI_JPEG_QUANTIZATION_TABLE'

            /* [out] */ __RPC__out DXGI_JPEG_QUANTIZATION_TABLE *pQuantizationTable) = 0;

                                   ^

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wincodec.h(8349): error: unknown type name 'DXGI_JPEG_AC_HUFFMAN_TABLE'

            /* [out] */ __RPC__out DXGI_JPEG_AC_HUFFMAN_TABLE *pAcHuffmanTable) = 0;

                                   ^

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wincodec.h(8354): error: unknown type name 'DXGI_JPEG_DC_HUFFMAN_TABLE'

            /* [out] */ __RPC__out DXGI_JPEG_DC_HUFFMAN_TABLE *pDcHuffmanTable) = 0;

                                   ^

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wincodec.h(8359): error: unknown type name 'DXGI_JPEG_QUANTIZATION_TABLE'

            /* [out] */ __RPC__out DXGI_JPEG_QUANTIZATION_TABLE *pQuantizationTable) = 0;

                                   ^
could not work around those yet.   It was fine before.  (also tried SDK 8.1, no change)

**Comment by hero101111** [comment] 2019-03-25 15:09
I am pleased that _CompileAs_ works as intended now.
Regarding the issues you're now encountering, please open a new Github Issue for this.
It would be best to attach a sample project to help us investigate the issue. 

Regards,
Gabriel.

**Comment by hero101111** [comment] 2019-03-25 15:13
>“Compile” used to work on active file in the editor, now always uses the current selection in the Solution explorer (even if it is closed)

This has already been addressed by us and will be fixed in the next release.
