### ISSUE TITLE
Unable to cancel clang-format for multiple files in case of error in .clang-format

### ISSUE THREAD

**Issue by Alexolut** [Caphyon/clang-power-tools#587] opened 2019-04-04 14:56 UTC
I'm using .clang-format file with `StatementMacros` key. This key is not known for default clang-format used by the clang-power-tools. (I don't know what is used by default, since I only installed Clang 9 in my system). When the path to clang-format.exe (9) is not specified in clang-power-tools settings, I've got the following error:

![2019-04-04 17_28_29-Microsoft Visual Studio](https://user-images.githubusercontent.com/12843204/55564182-fc3cc100-56ff-11e9-8101-12ea4263c8b3.png)

In case of requesting to format all files in solution I got new one error window as I clicked "Ok" button for every processed file. There is no way to cancel such operation without terminating the whole IDE or pressing Enter while files are exceeded. 

I know that this situation is rare, but for the bunch operation it would be good to have an option to cancel processing the rest of files. E.g another button near "Ok" named "Cancel all".

**Comment by Enache-Ionut** [comment] 2019-05-15 07:57
Hi, 

**Clang Power Tools** is always coming automatically with the **latest version of Clang Format**. In the next release, which will be **released this week**, **v4.10.4**, we will deliver the CPT extension with **Clang Format v8.0**. 

Unfortunately, if the behavior of the Clang Format is changed over time this is nothing we can do about it. This is why we introduced the option to add the path to the .exe file. In this way, the user can choose the best version for his needs.

**Regarding your issue**, if are you running clang format command when the file is not open the command will not currently work properly. We have this issue in progress and you can find more details about it here: https://github.com/Caphyon/clang-power-tools/issues/537. It seems for us that the issue occurred on your machine is actually the same issue.

In the case you are thinking this is a new bug can you tell us if you are using a **.clang-format** file in your project? Can you send us a simple project reproducing this issue with the .clang-format config file in it?

**Comment by Alexolut** [comment] 2019-05-15 08:27
I'm using not yet released Clang 9.0, hence some features used in `.clang-format` file are not recognized by Clang 8. To test the issue you just need add any typo in `.clang-format` file to make this file broken for clang-format utility. Then open a project/solution with enough number of files to process (my solution contains about 250 files (sources + headers)). A lot of files is needed to increase the time of clang-format procession and allow to user the time to cancel the long operation. But despite of existing a time, there is no way to cancel such an operation before all files were processed, since you will get an error popup (see my first post) and you need to close it manually for each file.

**Comment by Enache-Ionut** [comment] 2021-02-16 11:39
Hi,

In all this time, we made many changes to Clang Power Tools, a lot of new features and bug fixes are now available. Please check for updates. At this moment, the latest version is v7.1.

Can you tell us if this issue is still present on your machine?

**Comment by Enache-Ionut** [comment] 2021-03-12 09:17
I will close this issue because of the lack of information and because we cannot reproduce it anymore.

**Closed by Enache-Ionut** 2021-03-12 09:17 UTC
Labels: bug
