### ISSUE TITLE
[VS2019] VsWhere could not detect Visual Studio 2017 Microsoft.VisualStudio.Product.Enterprise

### ISSUE THREAD

**Issue by matbech** [Caphyon/clang-power-tools#543] opened 2019-03-02 22:32 UTC
On Visual Studio 2019 Preview 4 (RC), I get the following error when running compile or tidy:

VsWhere could not detect Visual Studio 2017 Microsoft.VisualStudio.Product.Enterprise.
At C:\users\mb\appdata\local\microsoft\visualstudio\16.0_a842d04d\extensions\ks1vy2qo.dxa\psClang\visualstudio-detectio
n.ps1:128 char:17
+ ...             throw "VsWhere could not detect Visual Studio $($global:c ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (VsWhere could n...uct.Enterprise.:String) [], RuntimeException
    + FullyQualifiedErrorId : VsWhere could not detect Visual Studio 2017 Microsoft.VisualStudio.Product.Enterprise.

I have no idea why clang-power-tools is looking for Visual Studio 2017.

**Comment by hero101111** [comment] 2019-03-03 08:23
Hello,

Please attach a *verbose* log so that we can further investigate this.
You can enable *Verbose logging* from the Clang Power Tools settings.

Regards,
Gabriel

**Comment by hero101111** [comment] 2019-03-04 12:36
I'm afraid we cannot reproduce this scenario, using _VS 2019 Preview 4_ and _CPT 4.8.1_. Does your project, by any chance, use platform toolset `v141`?

**Comment by hero101111** [comment] 2019-03-04 17:26
I'm closing this issue as it can no longer be reproduced.
Thank you for your feedback.

Regards,
Gabriel.

**Comment by bhardwajs** [comment] 2019-05-22 04:59
Is this supposed to recur when a project uses toolset `v141`? I am seeing error where vswhere is searching for MSVC 2017, but I don't have MSVC 2017 installed. I do have MSVC 2019 with both `v141` and `v142` toolsets.

**Comment by hero101111** [comment] 2019-05-22 13:23
Yes, Clang Power Tools will try to use Visual Studio 2017 for projects with `v141` toolset.
However, there's shouldn't be an error raised in your case, when only VS2019 is installed.

We're looking into it.

**Comment by bhardwajs** [comment] 2019-05-23 22:40
Should this issue be marked as open or would you like me to create a new issue? Please do let me know if I can provide anything to help debug.

**Comment by spaceyjase** [comment] 2019-09-20 10:57
I had an instance of this and the clang-build.ps1 scripts look like they do a test for the version in the default location; I had an empty folder in the default location so while it checked for '2017' (empty), it then caused an error because the version wasn't detected. Removing the folder seemed to fix everything (finding 2019, which is installed).

**Comment by Soyal7** [comment] 2019-09-21 17:29
I have the same issue when using CPT with VS 2019 in a project created in VS 2017. I had no previous VS 2017 installations before. Installing it fixes the problem.

**Comment by mttjcksn** [comment] 2021-04-27 12:26
Hi there, I'm using Microsoft Visual Studio Community 2019 Version 16.9.3.

I've just installed clang power tools and tried to run tidy on a file. I get this error:

VsWhere could not detect Visual Studio 2017 Microsoft.VisualStudio.Product.Community.

I'm not seeing a fix or relevant solution in this thread?

**Comment by hero101111** [comment] 2021-04-27 19:19
Hello @mttjcksn ,

It would be helpful to know which toolset is your project using.

Regards,
Gabriel

**Comment by mariru27** [comment] 2023-07-06 07:44
Hi @bhardwajs, @spaceyjase, @kd496, @mttjcksn,

Do you still have the same issue?

Kind regards,
Marina

**Comment by spaceyjase** [comment] 2023-07-06 07:59
Nope! Everything works these days :)

**Comment by mariru27** [comment] 2023-07-06 08:07
I am glad to hear that @spaceyjase, I will close this issue.

Thank you for your quick answer :))
If you find another problem, don't hesitate to open an issue

Have a nice day,
Marina

**Closed** 2023-07-06 08:07 UTC
Labels: bug, in progress
