### ISSUE TITLE
Cannot load extension on VS 2019

### ISSUE THREAD

**Issue by fotico** [Caphyon/clang-power-tools#998] opened 2021-10-04 10:44 UTC
Installed VS 2019 v16.11.3 with C++ Clang tools for windows v12
I then installed clang-powertools v7.6.0 and clangformat v12 from the extension dialog.

After installing the extensions and restarting visual studio, a dialog box informs me that "The RunClangPowerToolsPackage package did not load correctly". All the icons of the toolbar are greyed out.
The ActivityLog.xml shows the following entry:

```
<type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [RunClangPowerToolsPackage]Source: &apos;mscorlib&apos; Description: An error occurred while sending the request.&#x000D;&#x000A;</description>
```

I tried uninstalling the extension, deleting everything in %AppData%/ClangPowerTools (which was already empty), then reinstalling it - same thing happens.

**Comment by mariru27** [comment] 2021-10-04 13:49
Hi @fotico,

The problem is from Visual Studio, not from the extension.

But this may resolve your problem:
* Delete this folder: C:\Users[username]\appdata\local\microsoft\VisualStudio\16.0\ComponentModelCache

* An alternative from StackOverflow: https://stackoverflow.com/questions/31741405/error-setsite-failed-for-package-apachecordovatoolspackage

**Comment by SevHub** [comment] 2022-04-14 07:28
Hello, I am facing the same Problem with VS 2017 Express. I also deleted the extension and reinstalled, and deleted the ComponentModelCache directory, but the error still is there.

**Comment by mariru27** [comment] 2023-07-10 09:36
Hi @SevHub,

Do you still have the same problem?

Kind regards,
Marina

**Comment by mariru27** [comment] 2023-09-26 12:07
I'll be closing this issue due to insufficient information.

**Closed by mariru27** 2023-09-26 12:07 UTC
