### ISSUE TITLE
7.0.0 crashes on Visual Studio 2019 16.8.4

### ISSUE THREAD

**Issue by hamaney** [Caphyon/clang-power-tools#921] opened 2021-02-03 19:01 UTC
- extension 7.0.0
- VS2019 16.8.4
- Microsoft .NET Framework 4.804151

- started VS clicked on the  Settings icon (it is the only one active at this point) and vs crashes.

**Comment by Enache-Ionut** [comment] 2021-02-04 10:02
Hi, 

Thank you for your feedback!
We have some difficulties in reproducing this issue. Can you tell us if it was just a one-time problem? Is the issue consistent on your machine?

**Comment by hamaney** [comment] 2021-02-04 16:07
it is consistent so far. 
I have disabled all other extensions but I still see the crash.

could it be because I have a windows insider build?  My Os build is 21296.1010

**Comment by hamaney** [comment] 2021-02-05 06:10
It seems that the crash only happens on the setting click both (toolbar and context menu).
The rest of the icons are ok!

**Comment by MikeDiack** [comment] 2021-02-09 13:07
I am also having problems with Clang Power Tools 7 (see separate issue), Power Shell crash (am running Windows 8.1 x64). 6.5.0 is fine.

**Comment by MikeDiack** [comment] 2021-02-09 15:00
Note: Having got Clang Power Tools working, I've just seen this same crash when clicking the settings icon for Clang Power Tools.

I did get an exception dump though: See below:

Exception has been thrown by the target of an invocation. Object reference not set to an instance of an object.  --- EXCEPTION #1/3 [NullReferenceException] Message = “Object reference not set to an instance of an object.” ExceptionPath = Root.InnerException.InnerException ClassName = System.NullReferenceException HResult = E_POINTER=COR_E_NULLREFERENCE=80004003 Source = ClangPowerTools StackTraceString = “   at ClangPowerTools.PreinstalledLlvm.SetPathAndVersion(String path, String version)      at ClangPowerTools.PreinstalledLlvm.SetPreinstalledLlvm(String path, String version)      at ClangPowerTools.LlvmSettingsViewModel.IntitializeView()      at ClangPowerTools.LlvmSettingsViewModel..ctor(LlvmSettingsView view)      at ClangPowerTools.Views.LlvmSettingsView..ctor() ”  --- Outer ---  --- EXCEPTION #2/3 [TargetInvocationException] Message = “Exception has been thrown by the target of an invocation.” ExceptionPath = Root.InnerException ClassName = System.Reflection.TargetInvocationException InnerException = “Exception #1 at Root.InnerException.InnerException” HResult = COR_E_TARGETINVOCATION=80131604 Source = mscorlib StackTraceString = “   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)      at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)      at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)      at System.Activator.CreateInstance(Type type, Boolean nonPublic)      at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)      at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)      at System.Activator.CreateInstance(Type type, Object[] args)      at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)      at System.Xaml.Schema.SafeReflectionInvoker.CreateInstance(Type type, Object[] arguments)      at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)      at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)      at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)      at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)      at System.Xaml.XamlObjectWriter.WriteEndObject()      at System.Xaml.XamlWriter.WriteNode(XamlReader reader)      at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)      at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)      at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)      at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)      at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)      at ClangPowerTools.Views.SettingsView.InitializeComponent()      at ClangPowerTools.Views.SettingsView..ctor(Boolean showFooter)      at ClangPowerTools.Commands.SettingsCommand.<ShowSettingsAsync>d__6.MoveNext()   --- End of stack trace from previous location where exception was thrown ---      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)      at ClangPowerTools.CommandController.<LaunchCommandAsync>d__36.MoveNext()   --- End of stack trace from previous location where exception was thrown ---      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)      at ClangPowerTools.CommandController.<Execute>d__35.MoveNext()   --- End of stack trace from previous location where exception was thrown ---      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)      at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)      at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) ”  --- Outer ---  --- EXCEPTION #3/3 [LoggerException] Message = “Exception has been thrown by the target of an invocation.” ExceptionPath = Root ClassName = JetBrains.Util.LoggerException Data.ManagedThreadName = <NULL> InnerException = “Exception #2 at Root.InnerException” HResult = COR_E_APPLICATION=80131600 StackTraceString = “   at JetBrains.Application.Environment.HostParameters.InitStdWindowsAppFxHostMixin.<>c__DisplayClass0_0.<JetBrains.Application.Environment.HostParameters.IInitAppHostMixin.InitHost>b__0(Object sender, DispatcherUnhandledExceptionEventArgs args)      at System.Windows.Threading.DispatcherUnhandledExceptionEventHandler.Invoke(Object sender, DispatcherUnhandledExceptionEventArgs e)      at System.Windows.Threading.Dispatcher.CatchException(Exception e)      at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)      at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)      at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)      at System.Windows.Threading.DispatcherOperation.InvokeImpl()      at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)      at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)      at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)      at System.Windows.Threading.DispatcherOperation.Invoke()      at System.Windows.Threading.Dispatcher.ProcessQueue()      at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)      at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)      at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)      at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)      at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)      at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)      at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) ” 
---------------------------
OK   
---------------------------

**Comment by MikeDiack** [comment] 2021-02-09 15:43
Still seeing the failure to open the Settings window in CLang Power Tools 7.0.1 now.

**Comment by MikeDiack** [comment] 2021-02-09 15:45
Note: Although JetBrains Resharper is mentioned above, I'd actually suspended Resharper but it's crash handler caught the exception from Power Tools. It looks like it's failing when trying to ascertain the installed LLVM version.

**Comment by MikeDiack** [comment] 2021-02-09 17:02
Have debugged the crash using VS 2019 and the 7.0.1 master sources built from GitHub, crash is occuring at line 52:

See my comment CRASH HERE in the source code below:

System.NullReferenceException: 'Object reference not set to an instance of an object.'
llvmModel was null.

>	ClangPowerTools.dll!ClangPowerTools.PreinstalledLlvm.SetPathAndVersion(string path, string version) Line 52	C#

    private void SetPathAndVersion(string path, string version)
    {
      var settingsProviderLlvmModel = SettingsProvider.LlvmSettingsModel;
      var llvmModel = new LlvmModel();
      if ((string.IsNullOrWhiteSpace(settingsProviderLlvmModel.PreinstalledLlvmVersion) || string.IsNullOrWhiteSpace(settingsProviderLlvmModel.PreinstalledLlvmPath)) ||
        (!string.IsNullOrWhiteSpace(path) && !string.IsNullOrWhiteSpace(version) && version != settingsProviderLlvmModel.PreinstalledLlvmVersion))
      {
        llvmModel = llvms.Find(e => e.Version == version);
        llvmModel.HasPreinstalledLlvm = true; // CRASH HERE
        llvmModel.PreinstalledLlvmPath = path;

        settingsProviderLlvmModel.PreinstalledLlvmVersion = version;
        settingsProviderLlvmModel.PreinstalledLlvmPath = path;
      }
      else
      {
        llvmModel = llvms.Find(e => e.Version == settingsProviderLlvmModel.PreinstalledLlvmVersion);
        llvmModel.HasPreinstalledLlvm = true;
        llvmModel.PreinstalledLlvmPath = settingsProviderLlvmModel.PreinstalledLlvmPath;
      }

**Comment by Enache-Ionut** [comment] 2021-02-10 10:14
We are currently working on this issue. It will be fixed in the next release of Clang Power Tools. It's great to see this kind of interest for CPT. Thank you for your effort.

I'll update this thread when the issue we'll be fixed.

**Comment by MikeDiack** [comment] 2021-02-10 10:58
To reproduce BTW, all you need to do is delete the clang power tools roaming profile directory (%appdata%\ClangPowerTools) (i.e. simulating a virgin install of CPT) and then try either Clang Power Tools 6.5.0, 7.0.0 or 7.0.1. The settings button/window will crash as above.

**Comment by MikeDiack** [comment] 2021-02-10 11:58
Also might be relevant, I'm running LLVM 11.0.1.

**Comment by netx123** [comment] 2021-02-10 12:40
I was also having this exact same issue, I resolved the problem by uninstalling the pre installed version of LLVM that I had on the system, (LLVM-12.0.0-6923b0a7-win32.exe) LLVM Snapshot.
Once that version was uninstalled I was able to access CPT settings, I then used the inbuilt option to download LLVM 11.0.0, and everything is now working.

**Comment by MikeDiack** [comment] 2021-02-10 13:05
Note: A quick workaround type fix (I don't know if this is a proper solution) was to add my version of LLVM to the list in llvmversions.cs, and then rebuild and install the externsion e.g. in the list at the start of the llvmversions.cs file:
This does stop the crash occuring, but whether it's a "proper" solution I don't know....

namespace ClangPowerTools
{
  public class LlvmVersions
  {
    // Expected versions, if yours is not here, the settings Window might crash when you click on it!
    public static List<string> Versions { get; } = new List<string>
    {
      // START: Mike Diack added 12.0.0, 11.1.0 and 11.0.1 to prevent settings Window crashing if you have them installed.
      "12.0.0",
      "11.1.0",
      "11.0.1",
      // END: Mike Diack added 12.0.0, 11.1.0 and 11.0.1 to prevent settings Window crashing if you have them installed.
      "11.0.0",
      "10.0.0",
      "9.0.1",
      "9.0.0",
      "8.0.1",

**Comment by Enache-Ionut** [comment] 2021-02-10 14:56
The source of the issue is the LLVM version. We'll include support for the newer versions in the next version, along with a fix for this kind of situation.

**Comment by MikeDiack** [comment] 2021-02-11 14:26
Just tried the commit you've made today (11 Feb) to Master for this with VS 2019, 2017, 2015 using LLVM 11.0.1, 11.1.0 rc3 and 12.0.0 rc1. All are working. It looks good.

**Comment by Enache-Ionut** [comment] 2021-02-11 14:33
Great, thanks for testing 🎉 The official release will come soon.

**Comment by Enache-Ionut** [comment] 2021-02-12 14:05
Clang Power Tools v7.1 is now online. Please check for updates.

**Closed by Enache-Ionut** 2021-02-12 14:05 UTC
Labels: bug
