### ISSUE TITLE
Cannot find PCH

### ISSUE THREAD

**Issue by pwc357** [Caphyon/clang-power-tools#241] opened 2018-02-13 21:20 UTC
Here's the verbose output:

Start Clang Tidy

VERBOSE: clang-build.ps1 invocation args: 
  aVcxprojToCompile = C:\dev\xxx\yyy\Source\vc_projects\Math.vcxproj 
  aVcxprojConfigPlatform = Debug|x64 
  aClangCompileFlags = -Werror -Wall -fms-compatibility-version=19.10 -fms-compatibility -Wmicrosoft 
-Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-value 
  Verbose = True 
  aTidyFixFlags = 
-*,google-readability-redundant-smartptr-get,modernize-avoid-bind,modernize-loop-convert,modernize-make-shared,moderniz
e-make-unique,modernize-redundant-void-arg,modernize-replace-auto-ptr,modernize-replace-random-shuffle,modernize-shrink
-to-fit,modernize-unary-static-assert,modernize-use-emplace,modernize-use-equals-delete,modernize-use-nullptr,modernize
-use-transparent-functors,readability-container-size-empty,readability-misleading-indentation,readability-redundant-con
trol-flow,readability-redundant-declaration,readability-redundant-function-ptr-dereference,readability-redundant-member
-init,readability-redundant-smartptr-get,readability-redundant-string-cstr,readability-redundant-string-init,readabilit
y-uniqueptr-delete-release 
  aTidyHeaderFilter = .* 
  aVisualStudioVersion = 2017 
  aVisualStudioSku = Community 
  aSolutionsPath = C:\dev\xxx\yyy\Source\OfficeAll.sln 
  aDisableNameRegexMatching = True 
VERBOSE: CPU logical core count: 2
VERBOSE: Scanning for solution files
VERBOSE: Solution file paths:
VERBOSE:   C:\dev\xxx\yyy\Source\OfficeAll.sln
VERBOSE: Source directory: C:\dev\xxx\yyy\Source\
VERBOSE: Scanning for project files
VERBOSE: Found 105 projects
PROJECT: C:\dev\xxx\yyy\Source\vc_projects\Math.vcxproj
VERBOSE: Importing environment variables into current scope
VERBOSE: SET_VAR ALLUSERSPROFILE: C:\ProgramData
VERBOSE: SET_VAR APPDATA: C:\Users\paul\AppData\Roaming
VERBOSE: SET_VAR CommonProgramFiles: C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramW6432: C:\Program Files\Common Files
VERBOSE: SET_VAR COMPUTERNAME: OFFICEDT
VERBOSE: SET_VAR ComSpec: C:\WINDOWS\system32\cmd.exe
VERBOSE: SET_VAR FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
VERBOSE: SET_VAR FPS_BROWSER_USER_PROFILE_STRING: Default
VERBOSE: SET_VAR HOMEDRIVE: C:
VERBOSE: SET_VAR HOMEPATH: \Users\paul
VERBOSE: SET_VAR LOCALAPPDATA: C:\Users\paul\AppData\Local
VERBOSE: SET_VAR LOGONSERVER: \\OFFICEDT
VERBOSE: SET_VAR MSBuildLoadMicrosoftTargetsReadOnly: true
VERBOSE: SET_VAR NUMBER_OF_PROCESSORS: 2
VERBOSE: SET_VAR OneDrive: C:\Users\paul\OneDrive
VERBOSE: SET_VAR OS: Windows_NT
VERBOSE: SET_VAR Path: 
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program 
Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows 
Live\Shared;C:\Users\paul\AppData\Local\Microsoft\WindowsApps;C:\Program Files\LLVM\bin;
VERBOSE: SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
VERBOSE: SET_VAR PkgDefApplicationConfigFile: 
C:\Users\paul\AppData\Local\Microsoft\VisualStudio\15.0_6957cf2f\devenv.exe.config
VERBOSE: SET_VAR PROCESSOR_ARCHITECTURE: x86
VERBOSE: SET_VAR PROCESSOR_ARCHITEW6432: AMD64
VERBOSE: SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
VERBOSE: SET_VAR PROCESSOR_LEVEL: 6
VERBOSE: SET_VAR PROCESSOR_REVISION: 3c03
VERBOSE: SET_VAR ProgramData: C:\ProgramData
VERBOSE: SET_VAR ProgramFiles: C:\Program Files (x86)
VERBOSE: SET_VAR ProgramFiles(x86): C:\Program Files (x86)
VERBOSE: SET_VAR ProgramW6432: C:\Program Files
VERBOSE: SET_VAR PSExecutionPolicyPreference: Bypass
VERBOSE: SET_VAR PSModulePath: C:\Users\paul\Documents\WindowsPowerShell\Modules;C:\Program Files 
(x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
VERBOSE: SET_VAR PUBLIC: C:\Users\Public
VERBOSE: SET_VAR SESSIONNAME: Console
VERBOSE: SET_VAR SystemDrive: C:
VERBOSE: SET_VAR SystemRoot: C:\WINDOWS
VERBOSE: SET_VAR TEMP: C:\Users\paul\AppData\Local\Temp
VERBOSE: SET_VAR TMP: C:\Users\paul\AppData\Local\Temp
VERBOSE: SET_VAR USERDOMAIN: OFFICEDT
VERBOSE: SET_VAR USERDOMAIN_ROAMINGPROFILE: OFFICEDT
VERBOSE: SET_VAR USERNAME: paul
VERBOSE: SET_VAR USERPROFILE: C:\Users\paul
VERBOSE: SET_VAR VisualStudioDir: C:\Users\paul\Documents\Visual Studio 2017
VERBOSE: SET_VAR VisualStudioEdition: Microsoft Visual Studio Community 2017
VERBOSE: SET_VAR VisualStudioVersion: 15.0
VERBOSE: SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VERBOSE: SET_VAR VSAPPIDDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\
VERBOSE: SET_VAR VSAPPIDNAME: devenv.exe
VERBOSE: SET_VAR VSLANG: 1033
VERBOSE: SET_VAR VSSKUEDITION: Community
VERBOSE: SET_VAR windir: C:\WINDOWS
VERBOSE: SET_VAR MSBuildProjectFullPath: C:\dev\xxx\yyy\Source\vc_projects\AwrMath.vcxproj
VERBOSE: SET_VAR ProjectDir: C:\dev\xxx\yyy\Source\vc_projects\
VERBOSE: SET_VAR MSBuildProjectExtension: .vcxproj
VERBOSE: SET_VAR MSBuildProjectFile: Math.vcxproj
VERBOSE: SET_VAR MSBuildProjectName: Math
VERBOSE: SET_VAR MSBuildProjectDirectory: C:\dev\xxx\yyy\Source\vc_projects\
VERBOSE: SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
VERBOSE: SET_VAR ProjectName: Math
VERBOSE: SET_VAR TargetName: Math
VERBOSE: SET_VAR VisualStudioVersion: 15.0
VERBOSE: SET_VAR MSBuildToolsVersion: 15.0
VERBOSE: SET_VAR SolutionDir: C:\dev\xxx\yyy\Source\
VERBOSE: 
Sanitizing C:\dev\xxx\yyy\Source\vc_projects\Math.vcxproj
VERBOSE: SET_VAR MSBuildThisFileFullPath: C:\dev\xxx\yyy\Source\vc_projects\AwrMath.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: Math.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: Math
VERBOSE: SET_VAR MSBuildThisFileDirectory: C:\dev\xxx\yyy\Source\vc_projects\
VERBOSE: SET_VAR Configuration: Debug
VERBOSE: SET_VAR Platform: x64
VERBOSE: SET_VAR ProjectGuid: {9D581034-D580-49B0-89B9-4E3B2C467873}
VERBOSE: SET_VAR RootNamespace: Math
VERBOSE: SET_VAR WindowsTargetPlatformVersion: 10.0.15063.0
VERBOSE: Could not find property sheet \Microsoft.Cpp.Default.props
VERBOSE: SET_VAR ConfigurationType: DynamicLibrary
VERBOSE: SET_VAR PlatformToolset: v141
VERBOSE: SET_VAR UseOfMfc: false
VERBOSE: SET_VAR CharacterSet: MultiByte
VERBOSE: Could not find property sheet \Microsoft.Cpp.props
VERBOSE: Property sheet: C:\dev\xxx\yyy\common\private\debug.props
VERBOSE: 
Sanitizing C:\dev\xxx\yyy\common\private\debug.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: C:\dev\xxx\yyy\common\private\debug.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: debug.props
VERBOSE: SET_VAR MSBuildThisFileName: debug
VERBOSE: SET_VAR MSBuildThisFileDirectory: C:\dev\xxx\yyy\common\private\
VERBOSE: SET_VAR awrConfiguration: Debug
VERBOSE: SET_VAR awrConfigurationBin: Debug_x64
VERBOSE: SET_VAR LinkIncremental: true
VERBOSE: SET_VAR CodeAnalysisRuleSet: 
C:\dev\xxx\yyy\Source\\..\common\private\awr_NativeRecommendedRules.ruleset
VERBOSE: SET_VAR _ProjectFileVersion: 11.0.51106.1
VERBOSE: SET_VAR OutDir: .\..\..\..\Debug\simulators\
VERBOSE: SET_VAR IntDir: .\..\..\..\Debug\simulators\obj\Math\
VERBOSE: Could not find property sheet \Microsoft.Cpp.targets
VERBOSE: Force includes: 
VERBOSE: PCH cpp name: ..\StdAfx.cpp
VERBOSE: PCH header name: stdafx.h
Join-Path : Cannot find path 'C:\dev\xxx\yyy\Source\vc_projects\stdafx.h' because it does not exist.
At C:\Users\paul\AppData\Local\Microsoft\VisualStudio\15.0_6957cf2f\Extensions\wh41nkji.02o\clang-build.ps1:530 char:25
+ ... ]] $paths = Join-Path -Path "$base" -ChildPath "$child" -Resolve -Err ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\dev\MWOffice...ojects\stdafx.h:String) [Join-Path], ItemNotFoundExce 
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
 

Done Clang Tidy

Any ideas on how to troubleshoot? I'm running 2.7.0.

**Comment by cpp-red-lion** [comment] 2018-02-14 12:49
Hi,

Can you attach a sample project (with all required dependencies), so that we can reproduce this issue ?

Thanks.

**Comment by pwc357** [comment] 2018-02-16 16:17
In the process of making a simple project to reproduce, I discovered the root cause. There was a case mismatch between #include "stdafx.h" in the stdafx.cpp file and the actual case on disk (which was StdAfx.h). I know clang-tidy can report these differences but having it in the PCH caused a build error before it could be analyzed, I guess.

**Comment by cpp-red-lion** [comment] 2018-02-16 16:35
Thanks for the details.

**Comment by grisharav** [comment] 2018-02-27 08:37
This happens to me as well, if the precompiled header is not located near the project file. Is this a confirmed bug?

**Comment by cpp-red-lion** [comment] 2018-02-27 09:34
Hi @grisharav ,

The precompiled header is *not* required to be located near the project file (this is *not* a current limitation in _Clang Power Tools_).  

Your issue, although related to **PCH**, might be quite _different_ from the one described above.
To make sure we properly address **your** issue as well, please provide us with a _sample project_, so we can reproduce the behavior.

If you cannot provide us with a test project, you can wait until we fix the initial reported issue and then try the new version directly on your project, to see if it works.

**Comment by cpp-red-lion** [comment] 2018-02-27 09:36
FYI, attaching a _sample project_ reproducing the reported issue, always accelerates time to resolution for a bug 😉

**Comment by grisharav** [comment] 2018-02-27 18:33
[TestClangPowerTools.zip](https://github.com/Caphyon/clang-power-tools/files/1764208/TestClangPowerTools.zip)

Attached a small repro.

**Comment by cpp-red-lion** [comment] 2018-02-28 08:42
Thanks, @grisharav !
We'll look into it.

I'll update this thread when we have a fix.

**Comment by sephirostoy** [comment] 2018-03-06 08:00
I got the same issue. It's because in clang-build.ps1, in function Get-ProjectStdafxDir, you use -cmatch which expects a regular exception. However, in the path of the stdafx, there's a '\' character which should be escaped.

**Comment by hero101111** [comment] 2018-03-21 12:02
Hi,

We've identified the root cause and pushed a fix for it.
An updated version will be released today.

Thanks for the feedback.

Regards,
Gabriel

**Closed** 2018-03-21 12:33 UTC
Labels: bug
