### ISSUE TITLE
clang-tidy "cannot find given project(s)

### ISSUE THREAD

**Issue by brittj2001** [Caphyon/clang-power-tools#536] opened 2019-02-21 15:58 UTC
Clang Power Tools version 4.8.1 installed 2/21/2019.  

Attempting to run clang-tidy on a single file or multi-select of files results in the following error:

```
Start Clang Tidy

Cannot find given project(s)

Done Clang Tidy
```

It's worth noting that my solution file is at m:\local\jbritton.Bmcos.customattr_010719\ but my project files are under that directory plus src\mcos_impl\

**Verbose mode shows:**

```
Start Clang Tidy

VERBOSE: clang-build.ps1 invocation args: 
  aVcxprojToCompile = M:\local\jbritton.Bmcos.customattr_010719\matlab\src\mcos_impl\native_mcos_impl_win64.vcxproj 
  aCppToCompile = M:\local\jbritton.Bmcos.customattr_010719\matlab\src\mcos_impl\cos_core\ClassDefinitionManager.cpp 
  aVcxprojConfigPlatform = Debug|x64 
  aClangCompileFlags = -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas
 -Wno-unused-value 
  Verbose = True 
  aTidyFlags = 
-*,google-readability-braces-around-statements,google-readability-casting,google-readability-function-size,google-reada
bility-namespace-comments,google-readability-todo,modernize-avoid-bind,modernize-avoid-c-arrays,modernize-concat-nested
-namespaces,modernize-deprecated-headers,modernize-deprecated-ios-base-aliases,modernize-loop-convert,modernize-make-sh
ared,modernize-make-unique,modernize-pass-by-value,modernize-raw-string-literal,modernize-redundant-void-arg,modernize-
replace-auto-ptr,modernize-replace-random-shuffle,modernize-return-braced-init-list,modernize-shrink-to-fit,modernize-u
nary-static-assert,modernize-use-auto,modernize-use-bool-literals,modernize-use-default-member-init,modernize-use-empla
ce,modernize-use-equals-default,modernize-use-equals-delete,modernize-use-noexcept,modernize-use-nullptr,modernize-use-
override,modernize-use-transparent-functors,modernize-use-uncaught-exceptions,modernize-use-using,readability-avoid-con
st-params-in-decls,readability-braces-around-statements,readability-const-return-type,readability-container-size-empty,
readability-deleted-default,readability-delete-null-pointer,readability-else-after-return,readability-function-size,rea
dability-identifier-naming,readability-implicit-bool-conversion,readability-inconsistent-declaration-parameter-name,rea
dability-isolate-declaration,readability-magic-numbers,readability-misleading-indentation,readability-misplaced-array-i
ndex,readability-named-parameter,readability-non-const-parameter,readability-redundant-control-flow,readability-redunda
nt-declaration,readability-redundant-function-ptr-dereference,readability-redundant-member-init,readability-redundant-s
martptr-get,readability-redundant-string-cstr,readability-redundant-string-init,readability-simplify-boolean-expr,reada
bility-simplify-subscript-expr,readability-static-accessed-through-instance,readability-static-definition-in-anonymous-
namespace,readability-string-compare,readability-uniqueptr-delete-release,readability-uppercase-literal-suffix 
  aTidyHeaderFilter = .* 
  aVisualStudioVersion = 2017 
  aVisualStudioSku = Professional 
  aSolutionsPath = M:\local\jbritton.Bmcos.customattr_010719\jbritton.Bmcos.customattr_010719.sln 
VERBOSE: CPU logical core count: 12
VERBOSE: LLVM location: C:\Program Files\LLVM\bin
VERBOSE: Scanning for solution files
VERBOSE: Solution file paths:
VERBOSE:   M:\local\jbritton.Bmcos.customattr_010719\jbritton.Bmcos.customattr_010719.sln
VERBOSE: 
VERBOSE: Source directory: M:\local\jbritton.Bmcos.customattr_010719\
VERBOSE: Scanning for project files
VERBOSE: Found 0 projects
Cannot find given project(s)
VERBOSE: PROCESSING ALL PROJECTS
VERBOSE: Cleaning up PCH temporaries:
VERBOSE: 

Done Clang Tidy
```

**Comment by hero101111** [comment] 2019-03-07 23:06
Hello,

Unfortunately we cannot reproduce this issue. Please attach a sample `.sln` file to help us reproduce the problem. It seems that the solution project detection is at fault here.

Regards,
Gabriel

**Comment by hero101111** [comment] 2019-03-11 09:04
@brittj2001 Please provide a sample project/solution in order to help us investigate the issue.

Given the fact that we cannot reproduce the problem and no sample data is provided, we will soon label this issue as `Invalid` and close it.

**Comment by brittj2001** [comment] 2019-03-11 19:20
See the attached sln file.  Thanks!

[jbritton.Bmcos.customattr_010719.sln.txt](https://github.com/Caphyon/clang-power-tools/files/2953857/jbritton.Bmcos.customattr_010719.sln.txt)

**Comment by hero101111** [comment] 2019-03-11 19:32
Thank you for uploading the sample _sln_. We'll use it to further investigate the issue and get back with updates on this thread as soon as we have them.

**Comment by hero101111** [comment] 2019-03-11 20:19
I'm afraid even after reproducing your entire project directory layout we still cannot reproduce the issue.

Please run this command in a PowerShell window and let us know what it outputs:
`Test-Path "M:\local\jbritton.Bmcos.customattr_010719\matlab\src\mcos_impl\native_mcos_impl_win64.vcxproj"`

Do you have any special user access permissions rules set up?

**Comment by brittj2001** [comment] 2019-03-11 20:32
I do not have any special user access permissions set up.  The results of
the powershell command follow:

PS H:\> Test-Path
"M:\local\jbritton.Bmcos.customattr_010719\matlab\src\mcos_impl\native_mcos_impl_win64.vcxproj"
True
PS H:\>

**Comment by hero101111** [comment] 2019-03-11 21:12
We're going to need more verbose information to help us figure out what's going on here.

Please checkout the github sources for Clang Power Tools, we've just pushed a commit containing more verbose logging regarding the solution scanning process.

You'll need to replace `clang-build.ps1` and the `psClang` directory files from the _Visual Studio CPT extension directory_ (you'll find it somewhere under `%LOCALAPPDATA%` with the ones you downloaded from github.

After replacing the script files simply restart VS and try running CPT again with Verbose Logging. 
Please attach the new verbose log to this thread.

-Gabriel

**Comment by brittj2001** [comment] 2019-03-18 12:49
Sorry for the long delay.  I forgot about the email you sent and noticed it this weekend.  What follows is the output from a verbose run after replacing my `clang-build.ps1` and `psClang `directories files.


```
Start Clang Tidy

VERBOSE: clang-build.ps1 invocation args: 
  aVcxprojToCompile = M:\local\jbritton.Bmcos.customattr_031019\matlab\src\mcos_impl\native_mcos_impl_win64.vcxproj 
  aCppToCompile = M:\local\jbritton.Bmcos.customattr_031019\matlab\src\mcos_impl\cos_plugins\CustomMetaPluginImpl.cpp 
  aVcxprojConfigPlatform = Debug|x64 
  aClangCompileFlags = -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas
 -Wno-unused-value 
  Verbose = True 
  aTidyFlags = 
-*,google-readability-braces-around-statements,google-readability-casting,google-readability-function-size,google-reada
bility-namespace-comments,google-readability-todo,modernize-avoid-bind,modernize-avoid-c-arrays,modernize-concat-nested
-namespaces,modernize-deprecated-headers,modernize-deprecated-ios-base-aliases,modernize-loop-convert,modernize-make-sh
ared,modernize-make-unique,modernize-pass-by-value,modernize-raw-string-literal,modernize-redundant-void-arg,modernize-
replace-auto-ptr,modernize-replace-random-shuffle,modernize-return-braced-init-list,modernize-shrink-to-fit,modernize-u
nary-static-assert,modernize-use-auto,modernize-use-bool-literals,modernize-use-default-member-init,modernize-use-empla
ce,modernize-use-equals-default,modernize-use-equals-delete,modernize-use-noexcept,modernize-use-nullptr,modernize-use-
override,modernize-use-transparent-functors,modernize-use-uncaught-exceptions,modernize-use-using,readability-avoid-con
st-params-in-decls,readability-braces-around-statements,readability-const-return-type,readability-container-size-empty,
readability-deleted-default,readability-delete-null-pointer,readability-else-after-return,readability-function-size,rea
dability-identifier-naming,readability-implicit-bool-conversion,readability-inconsistent-declaration-parameter-name,rea
dability-isolate-declaration,readability-magic-numbers,readability-misleading-indentation,readability-misplaced-array-i
ndex,readability-named-parameter,readability-non-const-parameter,readability-redundant-control-flow,readability-redunda
nt-declaration,readability-redundant-function-ptr-dereference,readability-redundant-member-init,readability-redundant-s
martptr-get,readability-redundant-string-cstr,readability-redundant-string-init,readability-simplify-boolean-expr,reada
bility-simplify-subscript-expr,readability-static-accessed-through-instance,readability-static-definition-in-anonymous-
namespace,readability-string-compare,readability-uniqueptr-delete-release,readability-uppercase-literal-suffix 
  aTidyHeaderFilter = .* 
  aVisualStudioVersion = 2017 
  aVisualStudioSku = Professional 
  aSolutionsPath = m:\local\jbritton.Bmcos.customattr_031019\jbritton.Bmcos.customattr_031019.sln 
VERBOSE: CPU logical core count: 12
VERBOSE: LLVM location: C:\Program Files\LLVM\bin
VERBOSE: Scanning for solution files
VERBOSE: Caching solution file M:\local\jbritton.Bmcos.customattr_031019\jbritton.Bmcos.customattr_031019.sln
VERBOSE: Solution full path: M:\local\jbritton.Bmcos.customattr_031019\jbritton.Bmcos.customattr_031019.sln
VERBOSE: Solution data length: 8700
VERBOSE: Solution file paths:
VERBOSE:   M:\local\jbritton.Bmcos.customattr_031019\jbritton.Bmcos.customattr_031019.sln
VERBOSE: 
VERBOSE: Source directory: m:\local\jbritton.Bmcos.customattr_031019\
VERBOSE: Scanning for project files
VERBOSE: Retrieving project list for solution 
M:\local\jbritton.Bmcos.customattr_031019\jbritton.Bmcos.customattr_031019.sln
VERBOSE: Solution directory: M:\local\jbritton.Bmcos.customattr_031019\
VERBOSE: Intermediate solution project matches count: 0
VERBOSE: Found 0 projects
Cannot find given project(s)
VERBOSE: PROCESSING ALL PROJECTS
VERBOSE: Cleaning up PCH temporaries:
VERBOSE: 

Done Clang Tidy

```

Let me know how else I can help.  This tool would be awesome to work into our team's workflow.

**Comment by hero101111** [comment] 2019-03-20 12:45
Thanks for the updated log.

This pinpoints the problem to the *regex* that matches project names inside a *.sln* file.
However, on your sample sln, everything runs fine, I'm guessing your production _sln_ is somewhat different.

Please run the regex match tool of your liking (notepad++, [regexr.com](https://www.regexr.com), etc) on your .sln file content using the following expression: `Project\([{}\"A-Z0-9\-]+\) = \".*?\",\s\"(.*?)\"`. 
Matching should _not_ work. Are there any special characters which prevent the regex from working?

Regex match on your sample data: [regexr.com/4ajvr](https://www.regexr.com/4ajvr)

**Comment by brittj2001** [comment] 2019-03-20 12:48
The sln file I attached actually is my exact production sln.

**Comment by brittj2001** [comment] 2019-03-20 13:03
Additionally, pulling some data out of the verbose output I see the following variables:

aVcxprojToCompile = M:\local\jbritton.Bmcos.customattr_031019\matlab\src\mcos_impl\native_mcos_impl_win64.vcxproj 
  aCppToCompile = M:\local\jbritton.Bmcos.customattr_031019\matlab\src\mcos_impl\cos_plugins\CustomMetaPluginImpl.cpp
aSolutionsPath = m:\local\jbritton.Bmcos.customattr_031019\jbritton.Bmcos.customattr_031019.sln 

I have confirmed that the file `aCppToCompile` is contained within `aVcxprojToCompile` which is referenced within the `aSolutionsPath`.

**Comment by hero101111** [comment] 2019-03-25 15:04
The project data loading phase is not reached in your case. The issue resides with the scanning of the solution file. As long as this `Intermediate solution project matches count: 0` counter stays at 0, nothing else will work.

This counter depends exclusively on the matches of the regex I've asked you to run before.
When testing on the test .sln file you've provided, this counter is _not zero_.

If the .sln you're using in production is the same as the sample, I would ask you to try running ClangPowerTools on a different machine. There may be something wrong with your .NET / PowerShell installation.

-Gabriel.

**Closed** 2019-07-10 14:35 UTC
Labels: bug, need more info
