### ISSUE TITLE
KeyNotFoundException unhandled

### ISSUE THREAD

**Issue by madskristensen** [Caphyon/clang-power-tools#510] opened 2019-01-30 17:26 UTC
We're seeing and unhandled exception coming from Clang Power Tools in Visual Studio 2017 (15.9). The callstack doesn't tell us much except that it occurred here:

```
mscorlib.ni!System.Collections.Generic.Dictionary_2[[System.Int32,_mscorlib],[System.__Canon,_mscorlib]].get_Item
```

So it could be from accessing the dictionary defined in [OutputWindowConstants.cs](https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/Output/OutputWindowConstants.cs).

I can't share more information from the call stack, unfortunately. 

Let me know if you need any help.

Mads Kristensen
Visual Studio Extensibility Team

**Comment by Enache-Ionut** [comment] 2019-02-01 13:15
Hi,

I'm afraid I cannot reproduce this issue, but by taking a look at the code, I found several lines which raised a few suspicions. I made a fix which will be available in the next Clang Power Tools version (v4.7).

After you install the latest build coming out very soon could you please confirm the issue was solved and close it.

I will let you know when the CPT v4.7 will be online.

Best regards,
Ionut

**Comment by madskristensen** [comment] 2019-02-01 16:36
Excellent. Thank you very much! 👍

**Comment by Enache-Ionut** [comment] 2019-02-05 07:46
Clang Power Tools v4.7 is now online. Please let me know if the issue is still there.

**Closed** 2019-02-19 08:00 UTC
Labels: bug
