### ISSUE TITLE
format code incorrect

### ISSUE THREAD

**Issue by IronsDu** [Caphyon/clang-power-tools#1138] opened 2022-07-06 00:34 UTC
Hello.  I use clang-power-tools version 8.7.0.570 in VS2019 and VS2022.

This is my code
```c++
protected:
    TcpConnection(TcpSocket::Ptr socket,
                  size_t maxRecvBufferSize,
                  EnterCallback&& enterCallback,
                  EventLoop::Ptr eventLoop) BRYNET_NOEXCEPT
        :
#ifdef BRYNET_PLATFORM_WINDOWS
        mOvlRecv(port::Win::OverlappedType::OverlappedRecv),
        mOvlSend(port::Win::OverlappedType::OverlappedSend),
        mPostClose(false),
#endif
        mIP(socket->getRemoteIP()),
        mSocket(std::move(socket)),
        mEventLoop(std::move(eventLoop)),
        mAlreadyClose(false),
        mMaxRecvBufferSize(maxRecvBufferSize),
        mSendingMsgSize(0),
        mEnterCallback(std::move(enterCallback)),
        mHighWaterSize(0)
```

If i replace `BRYNET_NOEXCEPT` to `noexcept`, my code will change to :
```c++
protected:
    TcpConnection(TcpSocket::Ptr socket,
                  size_t maxRecvBufferSize,
                  EnterCallback&& enterCallback,
                  EventLoop::Ptr eventLoop) noexcept
        :
#ifdef BRYNET_PLATFORM_WINDOWS

          OvlRecv(port::Win::OverlappedType::OverlappedRecv),

          OvlSend(port::Win::OverlappedType::OverlappedSend),

          PostClose(false),
#endif

          IP(socket->getRemoteIP()),

          Socket(std::move(socket)),

          EventLoop(std::move(eventLoop)),

          AlreadyClose(false),

          MaxRecvBufferSize(maxRecvBufferSize),

          SendingMsgSize(0),

          EnterCallback(std::move(enterCallback)),

          HighWaterSize(0)
```

some code losed.

**Comment by IronsDu** [comment] 2022-07-06 00:36
Please help me, I already encounter this issues some times..  you can test my repo https://github.com/IronsDu/brynet/blob/master/include/brynet/net/TcpConnection.hpp

**Comment by mariru27** [comment] 2022-07-06 08:21
Hi,

Thank you for reporting this problem.

What style were you using when this happened?

You can try to format from the command line using clang-format.exe, version 14.0.3.
If the problem is still reproducing that means it is a problem from clang-format, and not from our extension.
In the above case you can report to llvm.

Let me know if this helped you 

Best regards,
Marina

**Comment by IronsDu** [comment] 2022-07-06 09:28
HI,
I try https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.ClangFormat, It's correct.

**Comment by hero101111** [comment] 2022-08-05 14:15
Closing this issue as there appears to be nothing we can fix on our end. For more information on how Clang Format works and to submit bugs regarding LLVM infrastructure, please head on to https://github.com/llvm/llvm-project

**Closed by hero101111** 2022-08-05 14:15 UTC
