### ISSUE TITLE
format error when the source code has **gbk** charset

### ISSUE THREAD

**Issue by paopaol** [Caphyon/clang-power-tools#603] opened 2019-04-26 13:41 UTC
### Original code
convert this from **utf-8** to **gbk**,and run clang format,
the formated result is Wrong indent.
```cpp
#include "mocker_vas.h"

#include <Windows.h>
#include <Winsock2.h>
#include <gmock/gmock.h>
#include <stdio.h>

using namespace ::testing;

//gbk中文
int main(int argc, char *argv[]) {
  auto mocker = TestMocker::getMocker();
               //gbk中文
  EXPECT_CALL(*mocker, bind(::testing::_, ::testing::_, ::testing::_))
      .WillOnce(Return(500))
      .WillOnce(Return(200))
      .WillOnce(Return(300));


  //auto vasMocker = hhtest::MockerVas::getMocker();

  //EXPECT_CALL(*vasMocker, GetVersion())
	 // .WillOnce(Return(vas::Version(1, 2, 3)))
	 // .WillOnce(Return(vas::Version(3, 2, 1)));

  printf("%d\n", ::bind(1, nullptr, 1));
  printf("%d\n", ::bind(1, nullptr, 1));
  printf("%d\n", ::bind(1, nullptr, 1));

  auto v123 = vas::fd::GetVersion();
  auto v321 = vas::fd::GetVersion();
  return 0;
}
```

### formated code
```cpp
#include "mocker_bind.h"
#include "mocker_vas.h"

#include <Windows.h>
#include <Winsock2.h>
#include <gmock/gmock.h>
#include <stdio.h>

using namespace ::testing;

// gbk中文
int main(int argc, char *argv[]) {
  auto mocker = TestMocker::getMocker();

  gb k中文
  EXPECT_CALL(*mocker, bind(::testing::_, ::testing::_, ::testing::_))
      .WillOnce(Return(500))
      .WillOnce(Return(200))
      .WillOnce(Return(300));



  to  vasMocker = hhtest::MockerVas::getMocker();

  //EXPE CT_CALL(*vasMocker, GetVersion())
	 
  WillOnce(Return(vas::Version(1, 2, 3)))
	 
  WillOnce(Return(vas::Version(3, 2, 1)));

  printf("%d\n", ::bind(1, nullptr, 1));
  printf("%d\n", ::bind(1, nullptr, 1));
  printf("%d\n", ::bind(1, nullptr, 1));

  auto v123 = vas::fd::GetVersion();
  auto v321 = vas::fd::GetVersion();
  return 0;
}

```

**Comment by Enache-Ionut** [comment] 2019-05-14 14:26
Hi,

First of all, I want to thank you for your interest in the Clang Power Tools Extension.

Unfortunately, this is a **Clang(LLVM) limitation**. To properly use the format command you must change the encoding of your files to UTF-8. This is not just a clang-format issue. The same constraint applies to the Clang Compile/Tidy/Tidy-Fix too.

I will close this issue because is nothing we can do to change the Clang behavior.

Regards,
Ionut Enache

**Comment by paopaol** [comment] 2019-05-15 14:28
but if i format the code file use clang-format in commmand line,the result is ok.
```sh
clang-format my-gbk.cpp
```
maybe it's not issue of **clang(LLVM)**

**Comment by paopaol** [comment] 2019-05-17 01:52
I am almost sure that it is not an issue of llvm,
because i add an **external tool** use **clang-format.exe** in visual studio,it works fine.
But I still hope to use **clang-power-tools** as my formatting tool, because he is really great.

**Comment by Enache-Ionut** [comment] 2019-05-17 07:38
I will reopen this issue and I will start to investigate this possibility. Thank you for your time and interest in our tool. I will update this thread immediately after we will make some progress.

**Comment by Enache-Ionut** [comment] 2019-05-23 09:46
Hi,

Can you send us a sample project reproducing the issue? We have difficulties in reproducing this issue.
In Visual Studio do you have all the files from your project in `Unicode` encoding or just the ones on which you try to apply clang format?

Also, please attach your `Format configuration` from the options page.

**Comment by paopaol** [comment] 2019-05-24 09:12
yes,
i was create a repo, https://github.com/paopaol/gbk-format this project could reproducing the issue

**Comment by Enache-Ionut** [comment] 2020-06-17 12:28
Hi @paopaol, 

Can you confirm the fix of this issue? In this scope please use the latest Clang Power Tools version, v6.0.1. 

We ran multiple tests on the given project using all the Clang Style options, and everything works as expected.

Regards,
~Ionut

**Comment by Enache-Ionut** [comment] 2020-08-26 13:13
I will close this issue due to lack of feedback. Everything works as expected and this issue is now fixed.

**Closed by Enache-Ionut** 2020-08-26 13:13 UTC
Labels: enhancement
