### ISSUE TITLE
Crash on update script action

### ISSUE THREAD

**Issue by mariru27** [Caphyon/clang-power-tools#1030] opened 2021-11-17 10:04 UTC

**Comment by hero101111** [comment] 2021-11-22 09:43
This crash is only reproducible when new PowerShell helper scripts are added, because they were ignored by the VS extension logic. 

#1032 addresses this issue, in order to provide a working solution to all versions that have the "Update PowerShell scripts". The update functionality will be transferred to clang-build.ps1, which will make sure its required bits are in place.

**Closed** 2021-11-22 09:43 UTC
Labels: bug
