### ISSUE TITLE
Will only run as Administrator

### ISSUE THREAD

**Issue by spudwa** [Caphyon/clang-power-tools#272] opened 2018-03-07 06:33 UTC
Start Clang Tidy

Add-Type : Could not find file 
'C:\Users\paul\AppData\Local\Temp\3kxibrdc.dll'.
At C:\Users\paul\AppData\Local\Microsoft\VisualStudio\15.0_69d310c0\Extensi
ons\ukhssf1u.zml\clang-build.ps1:286 char:1
+ Add-Type -TypeDefinition @"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], 
FileNotFoundException
    + FullyQualifiedErrorId : 
System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand
Exception setting "CursorPosition": "The Win32 internal error "No process is 
on the other end of the pipe" 0xE9 occurred while getting console output 
buffer information. Contact Microsoft Customer Support Services."
At line:3 char:1
+ $RawUI.CursorPosition = @{X=0;Y=0}
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
Cannot convert argument "fill", with value: "System.Collections.Hashtable", 
for "SetBufferContents" to type 
"System.Management.Automation.Host.BufferCell": "Cannot create object of type 
"System.Management.Automation.Host.BufferCell". Cannot convert null to type 
"System.ConsoleColor" due to enumeration values that are not valid. Specify 
one of the following enumeration values and try again. The possible 
enumeration values are "Black,DarkBlue,DarkGreen,DarkCyan,DarkRed,DarkMagenta,D
arkYellow,Gray,DarkGray,Blue,Green,Cyan,Red,Magenta,Yellow,White"."
At line:4 char:1
+ $RawUI.SetBufferContents(
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
Unable to find type [WorkloadType].
At C:\Users\paul\AppData\Local\Microsoft\VisualStudio\15.0_69d310c0\Extensi
ons\ukhssf1u.zml\clang-build.ps1:2204 char:34
+   [WorkloadType] $workloadType = [WorkloadType]::Compile
+                                  ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WorkloadType:TypeName) [], 
RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
Unable to find type [WorkloadType].
At C:\Users\paul\AppData\Local\Microsoft\VisualStudio\15.0_69d310c0\Extensi
ons\ukhssf1u.zml\clang-build.ps1:2208 char:22
+      $workloadType = [WorkloadType]::Tidy
+                      ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WorkloadType:TypeName) [], 
RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
PROJECT: C:\Users\paul\Downloads\run3consapp\RUN3ConsApp\RUN3ConsApp.vcxproj
Unable to find type [WorkloadType].
At C:\Users\paul\AppData\Local\Microsoft\VisualStudio\15.0_69d310c0\Extensi
ons\ukhssf1u.zml\clang-build.ps1:1970 char:55
+ ...                  , [Parameter(Mandatory=$true)][WorkloadType] $worklo ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (WorkloadType:TypeName) [], 
RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
The Win32 internal error "No process is on the other end of the pipe" 0xE9 
occurred while setting the console window title. Contact Microsoft Customer 
Support Services.
At line:1 char:1
+ PowerShell.exe -ExecutionPolicy Bypass -NoProfile -Noninteractive -co ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], HostException
    + FullyQualifiedErrorId : SetConsoleWindowTitle
 

Done Clang Tidy

Running as Administrator gives
Start Clang Tidy

WARNING: Could not find ssh-agent
PROJECT: C:\Users\paultait\Downloads\run3consapp\RUN3ConsApp\RUN3ConsApp.vcxproj
Set-Variable : Cannot overwrite variable HOME because it is read-only or constant.
At C:\Users\root\AppData\Local\Microsoft\VisualStudio\15.0_69d310c0\Extensions\iphbk0vm.1ss\clang-build.ps1:399 char:3
+   Set-Variable -name $name -Value $value -Scope Global
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (HOME:String) [Set-Variable], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotWritable,Microsoft.PowerShell.Commands.SetVariableCommand

**Comment by cpp-red-lion** [comment] 2018-03-07 07:13
Hi,

_Clang Power Tools_ does not require _**administrator privileges**_ to run.
I think there might be a problem with _Power Shell_ on your machine, maybe a **plugin** that gets loaded.

Have you tried running it on a different PC, or in a virtual machine ?

**Comment by cpp-red-lion** [comment] 2018-03-26 14:11
Any updates ?

**Comment by Enache-Ionut** [comment] 2019-05-15 08:50
Hi,

Unfortunately, we cannot reproduce this issue. How there are not any updates on it I will close it. Do not hesitate to reopen this issue if the problem will appear again in the future.

Thank you for taking the time and helping us make a better product.

**Closed by Enache-Ionut** 2019-05-15 08:50 UTC
Labels: need more info
