### ISSUE TITLE
Clang-format detector broken code view, doesn't detect rules

### ISSUE THREAD

**Issue by sirus20x6** [Caphyon/clang-power-tools#1214] opened 2022-11-23 19:20 UTC
First I tried this on wine and when it didn't work I just assumed it was a wine issue. then I tried it in a windows vm and no matter what cpp file I choose the never detects rules other than it thinks it was based on LLVM and a column limit. then in the next screen both code panels are broken

![image](https://user-images.githubusercontent.com/5103327/203629937-7918ae90-d7e1-4fdd-a2a3-a84c86d9af73.png)

**Comment by netx123** [comment] 2022-11-24 22:43
I've had a quick look into this, and I see the same issue.

I also noticed that if I continued to edit any of the base values, to trigger a refresh of the Format Preview, then an error was displayed in the preview pane:

C:\Users\\\*\*\*\*\AppData\Roaming\ClangFormatEditor\Format\23c29208-2c3d-406b-b76f-77a5df74d1d5\.clang-format:22:11: error: unknown enumerated scalar
Standard: Cpp14
                 ^~~~~
Error reading C:\Users\\\*\*\*\*\AppData\Roaming\ClangFormatEditor\Format\23c29208-2c3d-406b-b76f-77a5df74d1d5\.clang-format: invalid argument

For some reason the default value appearing in Standard: is "Cpp14", but for clang format the correct value should be "c++14"

Changing the Standard Value to "c++14" allowed the Preview Pane to show the expected results (However the left hand File pane still remains empty.)

**Comment by sirus20x6** [comment] 2022-12-02 19:11
Thanks! Sounds like a useful tool. I look forward to testing out the fix when available.

**Comment by mariru27** [comment] 2023-01-09 10:17
Hi @sirus20x6,

I cannot reproduce this problem, can you give me an file example?

Best regards,
Marina

**Comment by netx123** [comment] 2023-01-09 10:57
Hi @mariru27 , I've had another look at this,
Interestingly when trying to detect the format using a small file around 10K everything seems to work just fine,
But when I use larger files around 500K I can reproduce the issue.
Could the detector be timing out?

**Comment by mariru27** [comment] 2023-01-09 14:49
Thank you @netx123, after multiple attempts I could reproduce this issue.
Changing this Standard allowed the Preview Pane

We are working on a fix, I will return to you if any questions will appear in the process

Have a nice day,
Marina

**Comment by mariru27** [comment] 2023-01-12 08:53
Hi @sirus20x6, @netx123,

Can you test this [Clang Format Editor](https://drive.google.com/file/d/1-XaYnE9wR-s6D2O-lnOPIlsmXZoBbRBI/view?usp=sharing), and tell me if you meet any problems.

For me it resolved my problem with broken code view
But I cannot reproduce @sirus20x6 problem with LLVM, can you give me an example?

Best regards,
Marina

**Comment by netx123** [comment] 2023-01-12 09:58
Hi @mariru27 , I've tried that verion. I see that it does now set Standard to "Latest" but I also still get the same issue where both panes are blank when testing with some of my larger test files. Is there any logging I can turn on which I might be able to compare and provide to you?

**Comment by mariru27** [comment] 2023-01-12 10:02
Regretfully we don't generate a log, but can you give me a code example?

**Comment by netx123** [comment] 2023-01-12 10:07
Unfortunately as the code I have is part of a commercial project it's not something I can share. I'll attempt to trim down the code I have to something smaller and shareable and will let you know.

**Comment by mariru27** [comment] 2023-01-12 10:11
Thank you @netx123
I will continue to look into this issue

Have a nice day,
Marina

**Comment by netx123** [comment] 2023-01-12 17:37
I've been able to create a small file that produces a similar issue, here you'll see that the left pane only displays the first line of the source file:
[cpptest.zip](https://github.com/Caphyon/clang-power-tools/files/10404364/cpptest.zip)

The issue could be linked to the number of lines that the source and formatted files have, I was able to create a 100K file that consistently causes an expection in ClangFormatEditor (Sorry can't provide the source code, but heres a screenshot of the exception)
![FormatException](https://user-images.githubusercontent.com/8387938/212138797-ee2fbc37-f8dd-4f2d-aeee-0542cf463bbf.png)

**Comment by mariru27** [comment] 2023-01-13 07:54
Thank you @netx123

I am working on a fix

Best regards,
Marina

**Comment by mariru27** [comment] 2023-01-13 08:38
Hi @netx123, @sirus20x6,

Can you test [Clang Format Detector](https://drive.google.com/file/d/1F6u4E9huW3r-cOReL6ULw-70anyF470B/view?usp=sharing)?

Best regards,
Marina

**Comment by netx123** [comment] 2023-01-13 09:21
Hi @mariru27 , You've fixed the issue with the small test file cpptest.zip, that's working great.

However the larger file I have is still causing an exception:

Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at ClangFormatEditor.DiffMatchPatchWrapper.DetectOperationPerLine(String input, String output, List`1 inputOperationPerLine, List`1 outputOperationPerLine)
   at ClangFormatEditor.DiffMatchPatchWrapper.DiffAsFlowDocuments(String input, String output)
   at ClangFormatEditor.MVVM.Controllers.DiffController.CreateFlowDocumentAsync(String input, FormatStyle formatStyle, List`1 formatOptions, CancellationToken cancelToken)
   at ClangFormatEditor.MVVM.Controllers.DiffController.CreateFlowDocumentsAsync(List`1 filesContent, FormatStyle formatStyle, List`1 formatOptions, CancellationToken cancelToken)
   at ClangFormatEditor.MVVM.ViewModels.DetectorViewModel.DiffDocumentsAsync(List`1 filesPath, Window detectingWindowOwner)
   at ClangFormatEditor.MVVM.Views.DetectorView.ShowDiffAsync(List`1 filesPath, Window detectingWindowOwner)
   at ClangFormatEditor.MVVM.ViewModels.FileSelectorViewModel.DetectFormatStyleAsync()
   at ClangFormatEditor.TaskExtensions.SafeFireAndForget(Task task, Boolean continueOnCapturedContext, Action`1 onException)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ClangFormatEditor.App.Main()

**Comment by mariru27** [comment] 2023-01-13 09:23
Is the same exception?

**Comment by netx123** [comment] 2023-01-13 09:30
I beleive it's the same exception, it's System.ArgumentOutOfRangeException: Index was out of range, in the DetectOperationPerLine method (Same as the screenshot)

**Comment by mariru27** [comment] 2023-01-16 09:28
Hi @netx123,

Can you Test [Clang Format Detector](https://github.com/Caphyon/clang-format-editor/actions/runs/3928927260)? (from **Artifacts**)

Best regards,
Marina

**Comment by netx123** [comment] 2023-01-16 10:47
@mariru27 I've tested that version, it seems better, some of my smaller files (around 90K) no longer trigger the exception, however I still have larger files (around 500K) that do trigger the exact same exception.

**Comment by mariru27** [comment] 2023-01-16 13:19
Hi @netx123,

We planning a release with these bugfixes
I can't reproduce this bug, but you can give me a larger test file when you have one, and I will continue to investigate this problem

Thank you so much for your help

Have a nice day,
Marina

**Comment by netx123** [comment] 2023-01-16 13:55
Hi @mariru27 , I've been able to recreate the exception using a larger test file, I should be able to share this one, I'm just checking/anonymizing it and then will attach shortly.

**Comment by netx123** [comment] 2023-01-16 14:44
Hi @mariru27  Please find attached an example that triggers the exception 
[cpptestAnon.zip](https://github.com/Caphyon/clang-power-tools/files/10426753/cpptestAnon.zip)

**Comment by mariru27** [comment] 2023-01-18 07:24
Thank you @netx123, I will look into this problem soon

Best regards,
Marina

**Comment by mariru27** [comment] 2023-01-25 11:33
Hi @netx123, @sirus20x6,

Can you test [Clang Format Detector?](https://github.com/Caphyon/clang-format-editor/actions/runs/4005401502)

Best Regards,
Marina

**Comment by netx123** [comment] 2023-01-26 09:49
Hi @mariru27, That's working perfect now on all the files I've tested with.

**Comment by mariru27** [comment] 2023-01-26 09:53
Hi @netx123,

Thank you for all your help and for quick responses, this fix will be included in the next release

I will notify you here about next release

Have a nice day,
Marina

**Comment by mariru27** [comment] 2023-02-01 10:46
Hi @netx123, @sirus20x6,

The fix for this problem is available in release v2023 for Clang Power Tools and Clang-Format Editor

Thank you for your help, means a lot for our product

Have a nice day,
Marina

**Closed** 2023-02-02 07:35 UTC
Labels: bug
