### ISSUE TITLE
[VS2019] Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by raffaeler** [Caphyon/clang-power-tools#537] opened 2019-02-22 10:25 UTC
I first open a solution with a C++ project, when I click to "Clang Format", I get this error:
![image](https://user-images.githubusercontent.com/5183152/53236295-3b550c80-3694-11e9-9458-9ede7e59c3c4.png)

Version: 4.8.1
Visual Studio 2019 Preview 3

**Comment by Enache-Ionut** [comment] 2019-03-04 13:08
Hi, 

Unfortunately, we cannot reproduce this issue. Can you attach a sample project reproducing the issue?

**Comment by raffaeler** [comment] 2019-03-04 21:18
Hi, I upgraded to Preview 4 and now compilation works.
But when clicking on Clang Format, I get this other error dialog:
![image](https://user-images.githubusercontent.com/5183152/53763534-56f9b780-3ecb-11e9-90e5-dfeb1ef671ff.png)
I can try re-creating a repro, but it is not that simple because the vcproj was generated by GYP.

**Comment by Enache-Ionut** [comment] 2019-03-08 12:01
This issue persisted in the Clang Power Tools v4.9 too?

**Comment by raffaeler** [comment] 2019-03-09 14:16
The error is gone but I am not sure what to expect from clang-format.
I unformatted a region of my code (that can be compiled) and then pushed the button in the toolbar, but I don't see any action on code formatting. In other words the status bar tells me that "Clang-Format finished", but I see no differences in the text editor.

**Comment by Enache-Ionut** [comment] 2019-03-11 12:38
I tested the clang-format command on multiple projects. Unfortunately, we can not reproduce the bug. Can you send us a sample project reproducing the behavior you just described? Also can you please attach a screenshot with your Clang-Format option page?

**Comment by Yatagan1979** [comment] 2019-03-28 10:46
I have the same problem but on VS2017. When I run Clang Format on any project selected in Solution Explorer i get several the same error: "Error while running clang-format". I downloaded sources of Clang Power Tools and debug the problem ... by the wat, it was my first contact with C# :).
I noticed that if I open any cpp file from some project and then run Clang Format on this project from context menu I don't receive any errors. 
I check this method:
private void FormatAllSelectedDocuments(CommandUILocation commandUILocation)
and I noticed that ProjectItem.Document is always null, ok not always, when I opened some file then document != null.
I added this code and problem disappeared.
        var projectItem = item.GetObject() as ProjectItem;
        if (!projectItem.get_IsOpen(EnvDTE.Constants.vsext_vk_Code))
        {
            var window = projectItem.Open(EnvDTE.Constants.vsext_vk_Code);
            if (null != window)
            {
                window.Activate();
                window.Visible = true;
            }
        }
        var document = projectItem.Document;
Could you consider my fix?

**Comment by hprica** [comment] 2019-05-29 14:32
The issue will be fixed on v4.10.5.

**Comment by SilviuArdelean** [comment] 2019-06-19 08:33
I am using the v4.10.5 and the error is still reproducing while selecting few lines of code and clicking the Clang Format icon.

**Comment by hprica** [comment] 2019-06-19 08:36
@SilviuArdelean thank you for reporting the issue. I will take a look and get back to you.

**Comment by SilviuArdelean** [comment] 2019-06-19 08:38
> ok and get back to you

Please let me in case I may help with some info.

**Comment by SilviuArdelean** [comment] 2019-06-19 08:39
@hprica please let me in case I may help with some environment info.

**Comment by hprica** [comment] 2019-06-19 08:46
Just tested on our side, everything appears to work fine. Could you please provide a small sample with the issue?

**Comment by SilviuArdelean** [comment] 2019-06-19 09:12
I am reproducing this issue within a Chromium based project - Visual Studio 2017 (v15.9.13).
For instance, if I am opening the [brower_main.cc](https://cs.chromium.org/chromium/src/content/browser/browser_main.cc) and I am selecting only the **BrowserMain()** function and after that clicking the **Clang Format** file.

**Comment by NickYang1988** [comment] 2019-07-06 05:35
In VS2019 & clang-power-tools 5.0, this problem is still reproducing when I format the cpp file.

I put the .clang-format file at the root path of my project.

![image](https://user-images.githubusercontent.com/3690738/60752047-c820b700-9ff2-11e9-90a5-d66d140ad70d.png)
![image](https://user-images.githubusercontent.com/3690738/60752052-d7a00000-9ff2-11e9-804c-bf381e7ac68f.png)

Did I put the wrong path or this is a bug?

**Comment by NickYang1988** [comment] 2019-07-08 06:21
After I restart the VS2019, everything is fine.

**Comment by hprica** [comment] 2019-07-09 14:58
@SilviuArdelean I am still not able to reproduce the issue on my end. If it persists on your side please send a sample project so I can investigate further.

**Closed by hprica** 2019-07-09 14:58 UTC
Labels: bug

**Comment by hprica** [comment] 2019-07-10 06:42
@SilviuArdelean glad to hear you don't have the issue anymore and thank you for supporting CPT. If you have any other problems or feature suggestions let us know :)

**Comment by ivanrusl** [comment] 2024-01-02 17:52
The same problem: Clang format export error - object reference not set to an instance of an object. Mu version:  Visual studio 2022 и CPT 2023.9.0
