### ISSUE TITLE
Variable resolving does not work correctly if expression starts from $

### ISSUE THREAD

**Issue by tomektg** [Caphyon/clang-power-tools#496] opened 2019-01-10 18:54 UTC
The variable expanding mechanism used to preprocess projects and property sheets does not work correctly if the string to be expanded starts from the "$" symbol
e.g.
<AdditionalIncludeDirectories>$(AAA);$(BBB)</AdditionalIncludeDirectories>
"$(AAA);$(BBB);CCC"
gets expanded (assuming $(AAA) expanding to AAA and $(BBB) to BB) to 
"AAA BBB AAA;BBB;CCC"

This leads to ignoring the first include path and failing compilation.
Adding something other in front fixes the issue -> "DDD;$(AAA);$(BBB);CCC" expands correctly to "DDD;AAA;BBB;CCC"

The issue can be observed while building with clang-build.ps1 while printing "($data).InnerText" in the "Function Get-ProjectAdditionalIncludes". 

Moreover, strings are being executed during evaluation. 
Running clang-build.ps1 on a project that contains:
<OutputFile>msg * surprise $(OutDir)$(CombinedTargetFileName).lib</OutputFile>
Shows a surprise message. Quite funny :-), but also really dangerous

**Comment by hero101111** [comment] 2019-01-16 12:19
Hello,

I'm afraid I cannot reproduce this issue, as far as I understand your scenario. 

```
DEBUG: Start evaluate MSBuild expression $(aaa);$(bbb);CCC;
DEBUG: Evaluated expression to: AAA;BBB;CCC;
```

Is there something I'm missing?

**Comment by tomektg** [comment] 2019-01-21 16:57
Hi,
I've created a minimal example reproducing the problem
When I run it using .\clang-build.ps1 -dir ..., it won't compile (include not found) and shows a message (as on the attached screenshot)

I'm using power shell version 3. Maybe some other version is required?

[minimalExample.zip](https://github.com/Caphyon/clang-power-tools/files/2779811/minimalExample.zip)
![screen](https://user-images.githubusercontent.com/9948322/51488380-b1b8d300-1da5-11e9-864c-977e0615ac9b.png)

**Comment by hero101111** [comment] 2019-02-21 08:33
We've looked further into this; indeed the problem was occurring only on systems using PowerShell 3.0. Having isolated the issue, we were able to push a fix for it. It will be included in the next Clang Power Tools release (`4.9`).

Thank you for your feedback.

Regards,
Gabriel.

**Closed by hero101111** 2019-02-21 08:33 UTC
Labels: bug
