### ISSUE TITLE
Need 1:25s to compile one file - it seems regression compare to 1.*

### ISSUE THREAD

**Issue by mariusz102102** [Caphyon/clang-power-tools#130] opened 2017-11-29 22:46 UTC
I need 1:25s to compile one file from Visual Studio. My project folder is big:) ~ 10000 files, ~1000 folders - not everything included in Visual Studio solution.

Below timing (taken from verbose output) for most expensive steps
~5s - run clang-build.ps1 invocation args: 
~60s - Scanning for solution files
~10s - compile pch
~2s - compile file

Comments:
1. Why we have to scan for solution files? It seems like it is enough to use current solution. 
2. Is it possible to pass current solution to clang-build.ps1 without scanning?

Guys,
Thank you! Finally I was able compile and tidy my project!

**Comment by mariusz102102** [comment] 2017-11-29 23:37
Below some other ideas to speedup build/tidy:
1. Cache pch 
2. Compile pch only if changed

**Comment by cpp-red-lion** [comment] 2017-12-04 12:15
Scanning for solution files is a new thing we added in v2.0
This is the bit that introduced the compile-time regression in your case.
`~60s` is quite big :(

We'll try to workout a new strategy for identifying corresponding solutions.

**Comment by mariusz102102** [comment] 2017-12-04 23:06
Why we need scanning for solution at all?
We know which solution is opened in VS. We can just pass solution as parameter to clang-build.ps1. I would be even more restrictive and  make solution as mandatory parameter of clang-build.ps1

**Comment by hero101111** [comment] 2017-12-04 23:12
We need to set the `$(SolutionDir)` well known macro. That's all we need the solution for.
We have found, from user provided projects, that some projects require this macro in order to fully compile.

We're working on eliminating the scanning process when running clang-build.ps1 from the VS Extension, when the fully qualified solution name is known.

**Comment by cpp-red-lion** [comment] 2017-12-05 08:00
Solution scanning is required for CI/automation via the same PowerShell script that also drives the VS extension.
But, for the VS IDE workflow, @hero101111 has found a good solution that will fix the build time regression by eliminating unnecessary solution scanning, while maintaining backwards compatibility for the PS script.

Our next version will address this issue.
Thanks for pointing it out, @mariusz102102 👍

**Comment by cpp-red-lion** [comment] 2017-12-07 13:11
Fixed in version 2.1 
👍

**Closed** 2017-12-07 13:11 UTC

**Comment by gerboengels** [comment] 2018-02-16 12:59
Hello, I also noticed that scanning for solutions takes quite some time.
A fix that works for me, is using the `-Filter` option of `Get-ChildItem`.

```diff
diff --git a/clang-build.ps1 b/clang-build.ps1
index 8c8c37c8b..1c3a9236f 100644
--- a/clang-build.ps1
+++ b/clang-build.ps1
@@ -549,7 +549,7 @@ function Load-Solutions()
 {
    Write-Verbose "Scanning for solution files"
    $slns = Get-ChildItem -recurse -LiteralPath "$aSolutionsPath" `
-           | Where-Object { $_.Extension -eq $kExtensionSolution }
+           -Filter ("*" + $kExtensionSolution)
    foreach ($sln in $slns)
    {
      $slnPath = $sln.FullName
```
In my case it reduces the scanning-phase from 6s to 2s. This is nothing compared to the case of @mariusz102102, but it might speed things up significantly

**Comment by cpp-red-lion** [comment] 2018-02-16 13:16
Thanks for your improvement suggestion, @gerboengels 👍 

The *initial* issue on this thread was fixed in a totally different fashion, by altering the logic/workflow.
But your suggestion/optimization still applies to _VS solution scanning_ code.

I created a separate issue for this optimization you suggested: #247
