### ISSUE TITLE
Clang : Please use the /MD switch for _AFXDLL builds

### ISSUE THREAD

**Issue by Donaldpherman** [Caphyon/clang-power-tools#508] opened 2019-01-25 19:57 UTC
When I run Clang Power Tools->Compile on my projects that are DLL I get the above error.  As you can see from the screenshot below I have /MDd set so I don't understand why I'm getting this build issue.  My project builds fine with MSVC.  This is an MFC project.
![image](https://user-images.githubusercontent.com/3155787/51769410-cb089a80-2097-11e9-9e6a-ea27dbeabbf2.png)
![image](https://user-images.githubusercontent.com/3155787/51769582-53873b00-2098-11e9-97a7-03f2eb150b25.png)

**Comment by hero101111** [comment] 2019-02-21 09:57
Hello,

I'm afraid we cannot reproduce the issue. Please attach a sample project so that we can further investigate this.

Regards,
Gabriel.

**Comment by GerdHH** [comment] 2019-02-27 23:41
We're having the same issue on VC15.7.5.  Same as Donaldpherman, our RuntimeLibrary is set to Multi-threaded Debug DLL (/MDd)

I'm attaching a non-trivial project file with this issue.  Let me know if you need a simpler case to debug.
[FwSrv.zip](https://github.com/Caphyon/clang-power-tools/files/2912717/FwSrv.zip)

**Comment by hero101111** [comment] 2019-03-07 22:33
Hi again,

Thank you for helping us investigate this issue by attaching a sample project.
We've isolated the issue and pushed a fix; it'll be available in the next release of Clang Power Tools (`v5.0`).

Regards,
Gabriel.

**Closed by hero101111** 2019-03-07 22:33 UTC
Labels: bug

**Comment by hero101111** [comment] 2019-03-25 09:21
Hello again,

A quick update: We've had a bit of rescheduling of the release schedule and version `v4.10` was released a few days ago, instead of `v5.0`. Nonetheless, the fix _is_ included in `v4.10`.

Regards,
Gabriel.
