### ISSUE TITLE
Wrong stdafx.h included

### ISSUE THREAD

**Issue by elviiix** [Caphyon/clang-power-tools#487] opened 2018-12-13 07:34 UTC
When you are including cpp file from directory that contains stdafx.h from another project Visual Studio still includes correct (this project) stdafx.h, thereas Clang compile includes stdafx.h from file directory.

Project1 dir
  stdafx.h [1]
  file1.cpp
Project2 dir
  stdafx.h [2]
  includes file file1.cpp from Project1

in such case VS uses stdafx.h [2], and clang compile uses stdafx.h [1]

In attached example project test2 compiles ok in VS, but compiling fails in clang.

[test1.zip](https://github.com/Caphyon/clang-power-tools/files/2674915/test1.zip)

**Comment by hero101111** [comment] 2019-01-18 11:40
I've tested your sample project and the PCH detection and generation is working as intended, on our end.
```
VERBOSE: PCH header name: stdafx.h
VERBOSE: PCH directory: C:\cpt_sandbox\test1\test2\
VERBOSE: INVOKE: "C:\Program Files\LLVM\bin\clang++.exe" -include-pch "C:\cpt_sandbox\test1\test2.clang.pch" -x c++
"C:\cpt_sandbox\test1\test1\foo.cpp" -std=c++14  -m32 -fsyntax-only "-DWIN32" "-D_DEBUG" "-D_CONSOLE" -DUNICODE -D_UNICODE -D_DEBUG_FUNCTIONAL_MACHINERY
 -isystem"C:\cpt_sandbox\test1\test2" -isystem"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include"
-isystem"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include" -isystem"C:\Program Files (x86)\Windows
Kits\10\Include\10.0.17134.0\ucrt" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um" -isystem"C:\Program Files (x86)\Windows
Kits\10\Include\10.0.17134.0\shared" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\winrt" -isystem"C:\Program Files (x86)\Windows
Kits\10\Include\10.0.17134.0\cppwinrt" -I"C:\vcpkg\installed\x86-windows\include"
```
`clang` itself decides to include the _other_ `stdafx.h` because it's in proximity to `foo.cpp`, leading to the error you're experiencing:
```
2: C:\cpt_sandbox\test1\test1\foo.cpp
In file included from C:\cpt_sandbox\test1\test1\foo.cpp:1:
C:\cpt_sandbox\test1\test1/stdafx.h:13:2: error: test
#error test
 ^
1 error generated.

Got errors.
```
I'm not aware of a solution / workaround to this.

**Comment by hero101111** [comment] 2019-03-11 08:33
Hi again,

We've done some more testing regarding this issue and discovered a better workaround.
By using _angle brackets_ for including the PCH header (e.g. `include <stdafx.h>`) both _clang_ and _Visual C++_ are happy to include the header from the correct location.

We cannot issue a Clang Power Tools fix for this, you'll have to manually update your source files to use angle bracket includes for the PCH header. We've encountered this situation ourselves and resorted, successfully, to the workaround.

I hope you find this solution helpful to your workflow.

Regards,
Gabriel.

**Closed** 2019-03-11 08:57 UTC
Labels: bug, has workaround
