### ISSUE TITLE
Cannot perform tidy to header file.

### ISSUE THREAD

**Issue by taeguk** [Caphyon/clang-power-tools#185] opened 2017-12-27 04:49 UTC
```c++
// example.h
class A
{
public:
    virtual ~A() = default;
    virtual void func() = 0;
};
class B : public A
{
public:
    void func(); // 'override' is missing.
};
```

```c++
// example.cpp
#include "example.h"
void B::func() {}
```

I can't perform tidy to header file. I can only perform it to source file.
But the tidy operation to the source file cannot detect the problem that 'override' keyword is missing in the header file.

**Comment by jcageman** [comment] 2017-12-27 12:11
Compilation is done via source files and that is also how clang tidy works. You need a source file for it to work and depending on settings it will look at all headers included by the source file, none or only the own header etc. Probably best if you can't tidy a header at all.

**Comment by hero101111** [comment] 2017-12-28 13:56
Hello,

Headers can be also tidied alongside source files, by configuring the `Tidy > Header filter` setting:
 - `.*`                                    - _all project headers will be tidied_
 - `Corresponding Header` - _match current file name, tidying file.cpp will also tidy file.h_
 - `empty`                            - _no header will be tidied_

Unfortunately, there is a regression in v2.4.0 that broke this functionality.
We found the underlying issue and pushed a fix for it.

An updated version will be released today.

Thanks for your feedback

**Comment by taeguk** [comment] 2018-01-02 01:07
Directory structure:
```
SOLUTION_DIR/
    PROJECT_DIR/
        example.h
        example.cpp
````

```c++
// example.h
class A
{
public:
    virtual ~A() = default;
    virtual void func() = 0;
};
class B : public A
{
public:
    void func(); // 'override' is missing.
};
```

```c++
// example.cpp
#include "PROJECT_DIR/example.h"
void B::func() {}
```

@hero101111 Add ```$(ProjectDir)``` to 'Addtional Include Directories'. And then perform tidy to example.cpp. **Still 'example.h' which is a header file cannot be tidied.**

**Comment by hero101111** [comment] 2018-01-03 15:33
Can't reproduce what you're describing. 
Are you testing with the latest released version of Clang Power Tools (2.4.1)?

As a note, `$(ProjectDir)` is always added to include directories. 
Were you referring to adding `$(SolutionDir)` to *Additional Include Directories*?

**Comment by taeguk** [comment] 2018-01-04 00:08
@hero101111 Oh, sorry. That's my mistake. I wanted to say ```$(SolutionDir)```.
I tested with lastest (2.4.1). And I couldn't get the message which warns 'override' is missing.

**Comment by taeguk** [comment] 2018-01-09 10:10
@hero101111 This is my test case. (https://drive.google.com/open?id=1QovnBpws_4pCftmtYSAVVbXYdoJdSxXB)
I used "Visual Studio 2015 Update 3" with the clang-power-tools 2.4.1.

**Comment by hero101111** [comment] 2018-01-12 12:21
Hello again,

Thank you for the sample project; we've managed to reproduce the issue. 
The problem appears to be with _clang-tidy_, _not_ with _Clang Power Tools_.

First of all, Clang-Compile works so the header is reachable. 
We suspected the _header-filter regex and slash characters_ in the `#include` path are to blame. 
Turns out this is not the case since the header is tidied when included via the absolute file path.

Something internal to _clang-tidy_ prevents the tidy operation to be done on the header, if included via the parent directory (`#include "parentdir/example.h"`).

Unfortunately we don't have a solution for this issue until _clang-tidy_ resolves it.

Currently, headers will be tidied only if included by
- filename (`#include "example.h"`).
- absolute file path


Regards,
Gabriel

**Comment by taeguk** [comment] 2018-01-13 04:10
@hero101111 Hmm, I can't understand.
![image](https://user-images.githubusercontent.com/9107889/34902636-e30916fe-f862-11e7-9916-579735edb002.png)
I can tidy the header file with pure clang-tidy.

**Comment by cpp-red-lion** [comment] 2018-01-29 16:35
Hi,

This issue has been fixed in version `2.6` just released.

Thank you for your feedback 👍

**Closed by cpp-red-lion** 2018-01-29 16:35 UTC
Labels: bug, in progress

**Comment by taeguk** [comment] 2018-01-30 00:04
@cpp-red-lion Very thanks! 👍

**Comment by taeguk** [comment] 2018-01-30 04:25
Really thanks for your update! But still, I want more improvements.
In now, I can select only two options for "Treat additional includes as": "include directories" and "system include directories".
The problem is that all legacy projects use 'additional include directories' for adding include paths and I want to tidy header files in only a few paths.
The feature I want is filtering the paths to be tidied among paths specified in 'additional include directories'. And if the feature is added, as I think 'whitelist' way is more better. (The 'whitelist' way means registering only paths to be tidied and then unregistered paths don't be tidied.)
This is just for explaining my requirements. There may be more elegant way to satisfy my request.

**Comment by cpp-red-lion** [comment] 2018-01-30 07:41
Hi @taeguk ,

> Treat additional includes as:  _include directories_ or _system include directories_

This is not something we invented ourselves, in Clang Power Tools; we just leveraged an **_existing_** mechanism of specifying _include directories_ that **clang** uses to search for headers.

For more details, read our **Q&A** as part of the release notes on version `2.6`
https://github.com/Caphyon/clang-power-tools/blob/master/CHANGELOG.md

Unfortunately, **clang** does not have a mechanism for ignoring certain _directories_ when performing _tidy_ on a source file.
The only related mechanism that **clang-tidy** exposes is the `Header Filter` option, that you can configure via our _Settings_ panel (regex/wildcard for header names.extensions).

**Comment by cpp-red-lion** [comment] 2018-01-30 07:54
I just thought of a workaround for your "ignore a specific directory during tidy" issue:

Use a _custom_ `.clang-tidy` file in the directory you want to exclude, specifying no checks to perform there.
See details I wrote in issue: #218

**Comment by taeguk** [comment] 2018-01-30 07:55
@cpp-red-lion Yes, you're right. So what I want is handling some of **C/C++ - General - Additional Include Directories** like they are ```VC++ Directories - Include directories**. In other words, *passing some of **Additional Include Directories** to clang using **-isystem**.

**Comment by taeguk** [comment] 2018-01-30 08:00
@cpp-red-lion 
| Use a custom .clang-tidy file in the directory you want to exclude, specifying no checks to perform there.
Oh, Looks so awesome idea. I'll have a try :)

**Comment by taeguk** [comment] 2018-01-31 02:34
@cpp-red-lion I tried the way you suggested. But, it didn't work because the header files that I want to exclude are tided with the source files that I want to tidy.
Even if I put .clang-tidy file which disables all checks into the directory that I want to exclude, header files in the directory are still tidied with source files that exist in another directory I want to tidy.

**Comment by cpp-red-lion** [comment] 2018-01-31 10:16
If you explicitly include them from other directories, ... yeah I see what you mean.
Sorry, your only hope is `HeaderFilter`.
**clang-tidy** doesn't expose other mechanisms for dealing with this... :(

**Comment by taeguk** [comment] 2018-02-02 08:15
@cpp-red-lion Yes, you're right. So, what I want is that **ClangPowerTools** enables users to select the paths to be passed to clang with ```-isystem```.
In now, every *Additional Include Directories* are passed to clang with only ```-I```. But I want to use ```-isystem``` instead of ```-I``` for some of them.
For adapting to only **ClangPowerTools**, moving some of them from *C/C++ - General - Additional Include Directories* to *VC++ Directories - Include directories* is somewhat strange and very hard job for legacy project.
So, I want to suggest that **ClangPowerTools** add the feature that an user can pass some of *Additional Include Directories* to clang with **-isystem**.

**Comment by cpp-red-lion** [comment] 2018-02-02 13:29
We're reluctant to open that "door". Providing the ability to _explicitly specify include paths_ from Clang Power Tools settings, in addition to what we already extract from `vcxproj` and _property-sheets_ would only introduce confusion to users that don't require such a special setup. We actually had his option in the very first release version and people were confused by it.

For the moment, if modifying your `vcxproj` files is not an feasible option, your only workaround is to revert on the old behavior from version **2.5** by configuring the setting: 
`Clang Power Tools > General > Treat additional includes as > "system includes"`

**Comment by taeguk** [comment] 2018-03-21 06:18
@cpp-red-lion Long time no see. I'm very appreciated for steady and awesome updates on ClangPowerTools.
But I have not been able to introduce it to our company's legacy project because of the issue that we discussed about.

Let me explain my problem one more.
```c++
#include <extern_library_A/a.h>                   // Must NOT be tidied.
#include <extern_library_B/b.h>                   // Must NOT be tidied.
#include <myroot/some_my_header_1.h>   // Must be tidied.
#include <myroot/some_my_header_2.h>   // Must be tidied.

...
```
All include directories for those header files are specified in ```C/C++ > General > Additional Include Directory```.
I want that *extern_library_A/a.h* and *extern_library_B/b.h* are passed to ```-isystem``` and *myroot/some_my_header_1.h* and *myroot/some_my_header_2.h* are passed to ```-I```.
But I can't do that in current version of ClangPowerTools. What I can do is that all headers are passed to ```-isystem``` or that all headers are passed to ```-I```.
So, I suggested to provide the ability to explicitly specify include paths that are passed to ```-I```. But you was reluctant.

If you're still reluctant to provide that feature, I want to suggest another way.
The another way is passing all header files in vs project to ```-I``` for always tiding all header files in the vs project.

In above my example, *myroot/some_my_header_1.h* and *myroot/some_my_header_2.h* are specified in ```vcxproj```. But, *extern_library_A/a.h* and *extern_library_B/b.h* aren't.
Also, commonsensically, I think that all header files specified in ```vcxproj``` must be tidied.

How do you think about it? And thank you for listening to my suggestion.

**Comment by cpp-red-lion** [comment] 2018-03-26 08:27
Interesting suggestion, @taeguk 👍 
We'll think about it...

Thanks for not giving up on us :)

**Comment by taeguk** [comment] 2018-06-25 01:16
@cpp-red-lion Excuse me :) 
Could you let me know the progress of my suggestion?

**Comment by cpp-red-lion** [comment] 2018-06-25 07:28
Hi,

Unfortunately, no _immediate_ plans for this :(  
We are working hard on other reported issues, at the moment.  

But, we recently encountered a similar situation on our codebase, that we solved by moved a problem folder from _Additional Includes_ to _Include directories_.  Worked out OK for us.

**Comment by taeguk** [comment] 2018-11-08 07:50
@cpp-red-lion Excuse me. Still, is there no plan for this??

> moving a "problem folder" from Additional Includes to Include directories

is very limited solution.
If installing a package using package manager such as `nuget` and `conan`, property sheets are automatically included to a project and they add include directories to `C/C++ > General > Additional Include Directory`. So, in now, there is no suitable solution when using package manager.
So, I want that `ClangPowerTools` considers more about this problem. I think it is important issue in order that `ClangPowerTools` is used widely including in large scale projects.

Thanks.

**Comment by serenity320** [comment] 2019-02-25 02:36
I'm having a hard time right now because of the same problem. I hope it is improved. :)

**Comment by serenity320** [comment] 2019-02-25 02:39
I'm having a hard time right now because of the same problem.
I'm now using `nuget`, and property sheets of `nuget` packages add their include directories to `C/C++ > General > Additional Include Directory`.
I hope it will be resolved. :)
