### ISSUE TITLE
various errors when running Tidy Code option

### ISSUE THREAD

**Issue by abaldeva** [Caphyon/clang-power-tools#183] opened 2017-12-22 17:57 UTC
Hi,

I have VS 2015 Update 3 and version 2.4.0(12/21/2017). When I run Tidy Code, I see two main errors.

```
Exception calling "IsPathRooted" with "1" argument(s): "Illegal characters in path."
At C:\Users\abaldeva\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\wu15b2yr.etd\clang-build.ps1:514 char:7
+   if ([System.IO.Path]::IsPathRooted($child))
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ```

and it looks like the tool ignores the include directories of the VS project.

```
E:\work\blaze_dev\grpc_sample\source\clientmain.cpp(46): error: 'grpc/grpc.h' file not found [clang-diagnostic-error]
#include <grpc/grpc.h>
```
Any ideas? I am attaching the verbose log to the bug. Let me know if additional info is needed.

Thanks.
[clang_tidy_errors.txt](https://github.com/Caphyon/clang-power-tools/files/1583165/clang_tidy_errors.txt)

**Comment by hero101111** [comment] 2017-12-28 14:44
Hello,

Unfortunately, we're unable to reproduce this issue.
Please provide us with a project file we can investigate on.

Regards,
Gabriel

**Comment by cpp-red-lion** [comment] 2018-01-12 09:31
Hi,

@abaldeva  , can you provide us with a test project to debug ?
We don't seem to make any progress on this issue :(

I'm afraid I'm going to have to close it, if we don't have sufficient info to reproduce.

**Comment by cpp-red-lion** [comment] 2018-01-12 09:32
The MSBuild interpreter mechanism is able to put out an even more verbose log, called _debug log_.
Right now, we're not exposing this option in the VS Extension UI, as it is extremely verbose.

To activate debug mode you have to manually edit the `clang-build.ps1` script inside the VS extension directory. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Open the script in an editor and add the following line, after the script `Param()` block
`$DebugPreference = "Continue"`

Restart VS and compile again. You should see a more detailed log.

**Comment by cpp-red-lion** [comment] 2018-03-26 14:13
I'm going to close this issue, for lack of activity (extra information).
If the issue still persists and have more info, please re-open.

**Closed by cpp-red-lion** 2018-03-26 14:13 UTC
Labels: bug, need more info
