### ISSUE TITLE
Regular crashes in Visual Studio 2022

### ISSUE THREAD

**Issue by s-kipnis** [Caphyon/clang-power-tools#1099] opened 2022-03-06 10:38 UTC
Sometimes VS 2022 just disappears. This happnes quite irregular. VS 2022 may work nice a weak, but may crash every few minutes ten time in a row.
After restart of VS studio you get the message on the top 'Clang Tools crashed, disabling of the extension may help'
Disabling of the Clang Tools helps(probably not in 100% case).

LLVM - 13.0
Clang power tools 8.3.0.114
Visual Studio  latest

How could I help you guys? 2022 is critical for us, and clang-power-tools are critical too.

**Comment by mariru27** [comment] 2022-03-09 08:37
Hi

Are you using one of Clang Power Tools commands when Visual Studio crashes?

**Comment by s-kipnis** [comment] 2022-03-09 09:52
Not always.

Usually, VS crashes during auto-formatting. I see 'hourglass' mouse cursor, 'gray' VS window and in few seconds( or more ) crash follows(VS disappears).
But it is possible to get crash even when VS sits in background. The icon of VS on taskbar is just  OFF. This happens rare, but happens

After disabling of Clang Power Tools, I see no crashes.

**Comment by Bernhard-L** [comment] 2022-10-06 07:46
I have a similar behavior but VS doesn't crash it just blocks and doesn't respond anymore (so I have to kill the task).

If I disable "format on save" the endless loop does not occur. 
Formating the files explicitly works.
The best way to reproduce it (in my case) is to have a <changed and not saved> file, enabled "format on save" and then start compile (which makes a save).

I'm using VS2022 latest version ( 17.3.5 ) and the plugin Clan Power Tools 9.2.2.1998

**Comment by mariru27** [comment] 2022-10-06 08:44
Hi @Bernhard-L,

I can't reproduce this problem, can you try to make compile with [Clang Power Tools v9.2.1](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.2.1) and tell me if this issue is still reproducing?

Best regards,
Marina

**Comment by mariru27** [comment] 2022-10-06 08:59
Does this problem reproduce when you run Tidy command?

**Comment by Bernhard-L** [comment] 2022-10-07 07:29
> Hi @Bernhard-L,
> 
> I can't reproduce this problem, can you try to make compile with [Clang Power Tools v9.2.1](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.2.1) and tell me if this issue is still reproducing?
> 
> Best regards, Marina

As far as I remember, there was the same behaviour in the previous version.

But I reinstalled the version and checked again - and happens in this version, too (unsaved file, format on safe - start compile and VS isn't responding anymore)

maybe this is helpfull - we use a .clang-format file in the root of the project for the settings

**Comment by Bernhard-L** [comment] 2022-10-07 08:56
> Does this problem reproduce when you run Tidy command?

@mariru27 
I can't test this one, because clang tidy seems to have problems with VS cmake workspaces
`--- CLANG TIDY STARTED ---

In Zeile:1 Zeichen:131
+ ... \extensions\2hznqyzf.5v0\Tooling\\v1\clang-build.ps1' -proj ) -file ( ...
+                                                                 ~
Unerwartetes Token ")" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 

--- CLANG TIDY FINISHED ---`

**Comment by mariru27** [comment] 2022-10-07 09:29
@Bernhard-L

This problem happens from always or is it something that you discovered recently?

We know about this [bug in Visual Studio](https://developercommunity.visualstudio.com/t/BeforeSave-event-is-raised-after-save-ac/10156139?entry=problem) that broke our format on save feature. We made a release with a fix in version Clang Power Tools 9.2.1, after this, we noticed a weird behavior with documents that remained dirty on save, so we have released v9.2.2, and from my perspective, it is more probably to enter in a loop in this release(v9.2.2) that in previous.

If this happens before release v9.2.1, it is more probably to be from Visual Studio than our extension.

This is just an idea, this issue remains under investigation. I am still trying to reproduce this problem.

Also you can try an older [version v8.5](https://github.com/Caphyon/clang-power-tools/releases/tag/v8.5.0), or whatever version of Clang Power Tools that you remember that it worked fine.


Best regards,
Marina

**Comment by mariru27** [comment] 2022-10-07 09:36
@Bernhard-L 

Thank you for reporting this issue and responding so quickly

I will investigate more and return to you with some more questions if is needed

Have a nice day,
Marina

**Comment by mariru27** [comment] 2022-10-12 06:48
Hi @Bernhard-L,

Visual Studio has released version 17.3.6, with a bug fix for your problem. Can you try to update to the new version? 

You need to install an older version of Clang Power Tools, [v9.2](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.2).

Please let me know if this problem is still reproducing after that

Have a nice day,
Marina

**Comment by Bernhard-L** [comment] 2022-10-13 10:12
Hi @mariru27  ,
with the newest VS Version and Clang Power Tools 9.2 it doesn't block, but auto format on save with this version doesn't work (even when the switch is set to "on")
With the current Vsion 9.3.0.2043 I get the same behaviour

some dirty cpp files -> save all -> clag format on save -> all get formated and then compile is OK
some dirty cpp files -> compile -> auto save all -> maybe clang format on save - but VS blocks

**Comment by mariru27** [comment] 2022-10-14 10:01
Hi @Bernhard-L,

Can you try [this vsix](https://github.com/Caphyon/clang-power-tools/releases/tag/9.3.1) and tell me if the problem is still reproducing?

Best regards,
Marina

**Comment by Bernhard-L** [comment] 2022-10-18 15:28
@mariru27 
Hi, I tried the version 9.3.1.2054 the first test seemd to work, but the next tests ((again) one dirty file and two dirty files)
still blocked the VS when starting compile

same behavior, the file gets saved but the formating isn't performed

**Comment by Tyranisaur** [comment] 2022-10-27 14:25
For what it's worth, I'm experiencing this issue as well, while using Visual Studio 17.4 Preview versions.

Two days ago they release preview 5, https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#1740-pre50--visual-studio-2022-version-174-preview-5 which allegedly resolves this issue https://developercommunity.visualstudio.com/t/Visual-Studio-clears-dirty-flag-before-c/10124978 

However, I'm still experiencing issues with the clang-format on save feature from Clang Power Tools. I have issues both with version 9.3.0 and version 9.3.1 Sometimes format on save just doesn't work, but the file saves. And other times the IDE just hangs, which happened to me just now while trying to build with two dirty files.

**Comment by mariru27** [comment] 2022-11-09 08:28
Hi @Tyranisaur, @Bernhard-L,

Visual Studio made a fix for this issue in [release 17.4](https://developercommunity.visualstudio.com/t/BeforeSave-event-is-raised-after-save-ac/10156139)

I can't reproduce the problem.
Can you confirm that on Clang Power Tools [version 9.1 ](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.1) the problem is not reproducing?

Best regards,
Marina

**Comment by Tyranisaur** [comment] 2022-11-09 13:28
As far as I can tell, when using CPT 9.1 then Visual Studio doesn't hang after save with either 17.4 or 17.5 preview. However, the file doesn't get formatted.

Also, for reference, when using CPT 9.4 then format on save also doesn't work in either of the Visual Studio versions, but version 17.4 hangs, while version 17.5 preview doesn't hang.

**Comment by magnesj** [comment] 2022-11-10 05:57
Thanks for this fix, appreciate the quick response. Confirm working as expected with VS 17.4 and Clang Power Tools 9.4.1.

**Comment by mariru27** [comment] 2022-11-10 08:06
I am happy to hear this @magnesj
Because the problem is solved, I will close this issue

Thank you for helping us make this product better

Have a nice day,
Marina

**Closed** 2022-11-10 08:10 UTC
Labels: bug, cannot reproduce
