### ISSUE TITLE
vcpkg packages are not reachable

### ISSUE THREAD

**Issue by meastp** [Caphyon/clang-power-tools#267] opened 2018-03-02 12:57 UTC
I have generated a nuget-package with [vcpkg](https://github.com/Microsoft/vcpkg), and this file uses a **.targets**-file to insert includes etc. However, the includes are not found by clang-power-tools:

```xml
  <ItemDefinitionGroup Condition="'$(VcpkgEnabled)' == 'true'">
    <Link>
      <AdditionalDependencies Condition="'$(VcpkgNormalizedConfiguration)' == 'Debug' and '$(VcpkgAutoLink)' != 'false'">%(AdditionalDependencies);$(VcpkgRoot)debug\lib\*.lib</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(VcpkgNormalizedConfiguration)' == 'Release' and '$(VcpkgAutoLink)' != 'false'">%(AdditionalDependencies);$(VcpkgRoot)lib\*.lib</AdditionalDependencies>
      <AdditionalLibraryDirectories Condition="'$(VcpkgNormalizedConfiguration)' == 'Release'">%(AdditionalLibraryDirectories);$(VcpkgRoot)lib;$(VcpkgRoot)lib\manual-link</AdditionalLibraryDirectories>
      <AdditionalLibraryDirectories Condition="'$(VcpkgNormalizedConfiguration)' == 'Debug'">%(AdditionalLibraryDirectories);$(VcpkgRoot)debug\lib;$(VcpkgRoot)debug\lib\manual-link</AdditionalLibraryDirectories>
    </Link>
    <ClCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(VcpkgRoot)include</AdditionalIncludeDirectories>
    </ClCompile>
    <ResourceCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(VcpkgRoot)include</AdditionalIncludeDirectories>
    </ResourceCompile>
  </ItemDefinitionGroup>
```

My code uses boost from the nuget-package:

```
C:\development\QMS_Src\BaseModel\QsGeodataMod\Source\src\PersistentObject.cpp:10:10: fatal error: 'boost/uuid/uuid.hpp' file not found
#include <boost/uuid/uuid.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
```

Tell me if you need a vcpkg-made nuget-package to experiment with (with e.g. zlib).

**Comment by cpp-red-lion** [comment] 2018-03-02 13:10
Hi,

Thanks for bringing this to our attention 👍 

This is actually, the very first project we see using `vcpkg` with _Clang Power Tools_.
We were not aware of any issues, until now.

We'll investigate and I'll update this thread once we have a fix.

Victor

**Comment by gerboengels** [comment] 2018-03-02 22:20
Actually, issue #246 also comes from using vcpkg. This issue seems to be a duplicate of that one.

**Comment by Twon** [comment] 2018-03-21 11:08
Hi,

I'm also experiencing this issue with a manually generated Nuget packages.  If the props file in the Nuget package is using conditional statements in its evaluation then it does not work correctly.  For instance:

  <PropertyGroup Label="UserMacros" Condition="'$(Platform)'=='Win32'">
    <NagId>clw32261e</NagId>
    <NagBaseDir>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\lib\native'))\$(NagId)</NagBaseDir>
    <NagIncDir>$(NagBaseDir)\include</NagIncDir>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <ClCompile>
      <AdditionalIncludeDirectories>$(NagIncDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>

Results in headers not being located:
D:\git\#####.cpp:6:10: fatal error: 'nag.h' file not found
#include <nag.h>
         ^~~~~~~
1
 error
 generated.

But explicitly removing the conditionality in the MSBuild tags results in correct evaluation:

  <PropertyGroup Label="UserMacros">
    <NagId>clw32261e</NagId>
    <NagBaseDir>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\lib\native'))\$(NagId)</NagBaseDir>
    <NagIncDir>$(NagBaseDir)\include</NagIncDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(NagIncDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>

However in this case I have to select between differing location for header files based on 32-bit or 64-bit builds.

Kind regards,
Antony

**Comment by cpp-red-lion** [comment] 2018-03-21 12:30
Hi @Twon,

Thanks for your feedback.  

My colleague, @hero101111 is already investigating this. When we've made some progress, we'll update this thread.

**Comment by hero101111** [comment] 2018-07-03 11:09
Hello,

We're happy to inform you that we've fixed this and **vcpkg** packages are now detected by _ClangPowerTools_.
Version `3.7`, to be released today, will contain the fix.

Regards,
Gabriel

**Closed by hero101111** 2018-07-03 11:09 UTC
Labels: bug
