### ISSUE TITLE
Broken diff view in clang-format dector

### ISSUE THREAD

**Issue by technic** [Caphyon/clang-power-tools#1167] opened 2022-09-18 18:40 UTC
After changing clang-format rules in the style detector the diff becomes broken and the right panel (i.e. where the new output supposed to be becomes red).

**Comment by mariru27** [comment] 2022-09-19 06:53
Hi @technic,

Thank you for reporting this issue
Can you give us an example? 
What changes have you made in clang-format rules that brought you to this behavior?

Regards,
Marina

**Comment by technic** [comment] 2022-09-19 07:29
Hi, just any change in the rules. If you can't reproduce, I can send you a screenshots and create an example project. Currently I tried on our internal project which I can't share. 
Thanks.

**Comment by mariru27** [comment] 2022-09-19 07:55
I can't reproduce this problem, so please send us an example when you find time

Regards,
Marina

**Comment by mariru27** [comment] 2023-02-03 14:06
Hi @technic,

The fix for this problem is available in [release v2023](https://clangpowertools.com/CHANGELOG.html) for Clang Power Tools and Clang-Format Editor

Thank you for reporting this issue

Have a nice day,
Marina

**Closed** 2023-02-03 14:07 UTC
Labels: bug
