### ISSUE TITLE
clang-format on save prompts to save contents of Output window

### ISSUE THREAD

**Issue by nrs-mparker** [Caphyon/clang-power-tools#1190] opened 2022-10-13 20:04 UTC
Getting this bug constantly for the first time today.  When I have unsaved changes to a file and hit my keyboard shortcut to build my startup project, I sometimes get a Save File As dialog that prompts me to save "Output-Build.txt" to C:\Users\username\source\repos.  If the Output window was set to, say, Build Order instead, then it prompts for "Output-BuildOrder.txt".  When I press Cancel on that dialog, I get a message box with the title Clang Power Tools and the message "Error while running clang command on save. User canceled out of save dialog (Exception from HRESULT: 0X8004000C (OLE_E_PROMPTSAVECANCELLED))".  I can make it happen at least every-other time I try with a one-character change, but it feels like earlier it sometimes happened multiple edits in a row.  Not sure 100% if that did happen.

VS version: 17.3.6
CPT version: 9.3.0.2043
Windows version: 10 Enterprise, 20H2, 19042.2006

Please let me know if there is any other helpful info I can provide.

**Comment by mariru27** [comment] 2022-10-14 06:16
Hi @nrs-mparker,

Thank you for reporting this issue

By the way, do you notice if this problem started reproducing after the Visual Studio update 17.3.6?
This problem is under investigation.

Best regards,
Marina

**Comment by mariru27** [comment] 2022-11-09 08:43
Hi @nrs-mparker 

Visual Studio made a fix for this issue in [release 17.4](https://developercommunity.visualstudio.com/t/BeforeSave-event-is-raised-after-save-ac/10156139)

I can't reproduce the problem.
Can you confirm that on Clang Power Tools [version 9.1 ](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.1) the problem is not reproducing?

Best regards,
Marina

**Comment by nrs-mparker** [comment] 2022-11-09 17:41
At some point, I stopped being able to reproduce this without realizing it.  It definitely happened for at least a few more days after my last comment, but I am still on VS 17.3.6 and CPT 9.3.1.2054, and it seems to have resolved itself somehow.  I will probably update to VS 17.4.0 and CPT 9.4.1 today, but I don't expect the problem to return.  Thank you for letting me know.

**Closed** 2022-11-10 08:10 UTC
Labels: bug
