### ISSUE TITLE
Clang power tool exits Visual Studio 2019 when one clicks Tidy

### ISSUE THREAD

**Issue by kingofthebongo2008** [Caphyon/clang-power-tools#804] opened 2020-05-12 07:41 UTC

**Comment by Enache-Ionut** [comment] 2020-05-13 08:40
Hi, 

Can you tell us a few information about your environment as:
- What version of Clang Power Tools are you running? 
- What version of Visual Studio 2019 are you using?
- The issue occurred after an update or is the first time are you using Clang Power Tools? 
- Can you attach a project which has this issue?

**Comment by kingofthebongo2008** [comment] 2020-05-13 16:30
Version is 16.5.4

I have got an update today, it exited also.
I am not sure it is crashing, looks like it is telling visual studio to close

**Comment by kingofthebongo2008** [comment] 2020-05-13 16:36
It looks like to be a specific project. I

**Comment by Enache-Ionut** [comment] 2020-05-14 12:21
In order to make a full reset of Clang Power Tools try the following steps:
1. Close all Visual Studio entities
2. Go to `%appdata%` and delete the entire `ClangPowerTools` folder
3. Open Visual Studio and try to execute the Tidy command (you will be prompted to enter your credentials again) 

If the issue is still is important for us to know the followings:
- Do you have a CMake project or a .sln based project?
- The issue occurred after an update or is the first time are you using Clang Power Tools?
- A sample project which has this issue will be a great help for us. Can you attach one?

**Comment by kingofthebongo2008** [comment] 2020-05-14 14:56
Does this help?

The thread 0x36e8 has exited with code 0 (0x0).
onecore\com\combase\dcomrem\marshal.cxx(1282)\combase.dll!77ACFC21:
(caller: 77ACF57C) ReturnHr(1) tid(34b0) 80004002 No such interface
supported
    Msg:[Failed to marshal with IID={803E46E2-6A0D-4D5D-9F84-6CE1248B068D}]
onecore\com\combase\dcomrem\marshal.cxx(1177)\combase.dll!77ACF715:
(caller: 77ACD854) LogHr(1) tid(34b0) 80004002 No such interface supported
onecore\com\combase\dcomrem\marshal.cxx(1117)\combase.dll!77ACD8AA:
(caller: 77AC6474) ReturnHr(2) tid(34b0) 80004002 No such interface
supported
'devenv.exe' (Win32): Loaded
'C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll'. Symbol
loading disabled by Include/Exclude setting.
System.Transactions Critical: 0 : <TraceRecord xmlns="
http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord"
Severity="Critical"><TraceIdentifier>
http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled
exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.Runtime.InteropServices.COMException,
mscorlib, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Unspecified error
(Exception from HRESULT: 0x80004005 (E_FAIL))</Message><StackTrace>   at
EnvDTE.Documents.SaveAll()
   at
ClangPowerTools.ClangCommand.&amp;lt;PrepareCommmandAsync&amp;gt;d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
ClangPowerTools.Commands.CompileCommand.&amp;lt;RunClangCompileAsync&amp;gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
ClangPowerTools.CommandController.&amp;lt;LaunchCommandAsync&amp;gt;d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
ClangPowerTools.CommandController.&amp;lt;Execute&amp;gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at
System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_0(Object
state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at
System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object
state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object
obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at
MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32
msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority
priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr
wParam, IntPtr
lParam)</StackTrace><ExceptionString>System.Runtime.InteropServices.COMException
(0x80004005): Unspecified error (Exception from HRESULT: 0x80004005
(E_FAIL))
   at EnvDTE.Documents.SaveAll()
   at
ClangPowerTools.ClangCommand.&amp;lt;PrepareCommmandAsync&amp;gt;d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
ClangPowerTools.Commands.CompileCommand.&amp;lt;RunClangCompileAsync&amp;gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
ClangPowerTools.CommandController.&amp;lt;LaunchCommandAsync&amp;gt;d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
ClangPowerTools.CommandController.&amp;lt;Execute&amp;gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at
System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_0(Object
state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at
System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object
state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object
obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at
MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32
msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority
priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr
wParam, IntPtr
lParam)</ExceptionString><DataItems><Data></Data></DataItems></Exception></TraceRecord>
An unhandled exception of type
'System.Runtime.InteropServices.COMException' occurred in mscorlib.dll
Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))

**Comment by Enache-Ionut** [comment] 2020-06-03 09:56
Hi, 

This issue is fixed and it will be available in the new version of Clang Power Tools, v6.0, which will be released very soon. 

Thank you for your feedback!

Regards, 
~ Ionut

**Closed by Enache-Ionut** 2020-06-03 09:56 UTC
Labels: bug
