### ISSUE TITLE
SanitizeProjectNode's ItemDefinitionGroup processing ignores Conditions

### ISSUE THREAD

**Issue by kornman00** [Caphyon/clang-power-tools#1230] opened 2023-01-05 03:36 UTC
I have the following in a shared .props file which my vcxproj files import:
```xml
	<ItemDefinitionGroup>
		<ClCompile>
			<DebugVisualStudioVersion>$(VisualStudioVersion)</DebugVisualStudioVersion>
			<LanguageStandard>stdcpp17</LanguageStandard>
			<!--VS2022-->
			<LanguageStandard Condition="$(VisualStudioVersion)=='17.0'">stdcpp20</LanguageStandard>
```

I was scratching my head wondering why I was getting the following output under VS2017 (hence why I added DebugVisualStudioVersion)
```
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: [CONTEXT] propSet: DebugVisualStudioVersion = 15.0
VERBOSE: [CONTEXT] propSet: LanguageStandard = stdcpp17
VERBOSE: [CONTEXT] propSet: LanguageStandard = stdcpp20
```

In SanitizeProjectNode, there's this code
```ps1
    if ($node.Name -ieq "ItemDefinitionGroup")
    {
        foreach ($child in $node.ChildNodes)
        {
            if ($child.GetType().Name -ine "XmlElement")
            {
                continue
            }

            Push-ProjectItemContext $child.Name

            foreach ($propNode in $child.ChildNodes)
            {
                if ($propNode.GetType().Name -ine "XmlElement")
                {
                    continue
                }

                [string] $propVal = Evaluate-MSBuildExpression $propNode.InnerText
                Set-ProjectItemProperty $propNode.Name $propVal
            }

            Pop-ProjectItemContext
        }
    }
```

Unlike in other places, `$propNode` is not tested to see if it contains a Condition attribute, so CPT ends up evaluating all properties, no matter what.

This also makes settings which inherit previous values pile up
```xml
<PreprocessorDefinitions Condition=" '$(Configuration)' == 'Debug' ">_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
<PreprocessorDefinitions Condition=" '$(Configuration)' != 'Debug' ">NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
```

Both debug and no debug 😨 
```
VERBOSE: [CONTEXT] propSet: PreprocessorDefinitions = _DEBUG;
VERBOSE: [CONTEXT] propSet: PreprocessorDefinitions = NDEBUG;_DEBUG;
```

**Comment by mariru27** [comment] 2023-01-05 11:34
Hi @kornman00,

Thank you for reporting this issue
We working on a fix for this problem

Have a nice day,
Marina

**Comment by hero101111** [comment] 2023-01-05 12:28
Hi @kornman00 ,

We are unable to reproduce the behavior, as currently reported.
The `SanitizeProjectNode` recursive method that you referenced takes care to exclude child nodes, regardless or current node name, _if_ they have a Condition attribute evaluated to False. On our internal test projects, the mechanism works as intended, including on `ItemDefinitionGroup` and `PreprocessorDefinitions` elements.

Something else must be happening in your scenario. Please attach a sample project that we can use to further investigate this issue and find out the underlying cause.

**Comment by kornman00** [comment] 2023-01-05 18:00
It may take me a while to throw together a sample project if you need it.

Do your internal test projects operate on `.props` files which contain ClCompile and conditional properties? That is my first guess where this is falling apart.

SanitizeProjectNode only evaluates child node conditions in the 2nd to last foreach loop: https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/Tooling/v1/psClang/msbuild-project-load.ps1#L607

However, ItemDefinitionGroup, and its inner loop which would ultimately handle ClCompile/Link/Lib/etc, is handled before this https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/Tooling/v1/psClang/msbuild-project-load.ps1#L557. Because of that, it calls `Set-ProjectItemProperty` without processing any conditionals. `ParseProjectFile` calls `SanitizeProjectNode` directly.

Here's a more complete snippet of the `SharedLibs.props` file which my vcxproj file imports.
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<!--This file is included AFTER Microsoft.Cpp.props and Microsoft.Cpp.$(Platform).user.props-->

	<ItemDefinitionGroup>
		<ClCompile>
			<DebugConfiguration>$(Configuration)</DebugConfiguration>
			<DebugVisualStudioVersion>$(VisualStudioVersion)</DebugVisualStudioVersion>
			<LanguageStandard>stdcpp17</LanguageStandard>
			<!--VS2022-->
			<LanguageStandard Condition="$(VisualStudioVersion)=='17.0'">stdcpp20</LanguageStandard>
```

A snippet of the .vcxproj, `SharedLibs.props` is the very last Import show here:
```xml
  <Import Project="$(SharedLibsProjectSettingsDir)\SharedLibs.Cpp.Default.props" />
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Label="Configuration">
    <ConfigurationType>StaticLibrary</ConfigurationType>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <Import Project="$(SharedLibsProjectSettingsDir)\SharedLibs.Cpp.props" />
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="Shared">
  </ImportGroup>
  <ImportGroup Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(SharedLibsProjectSettingsDir)\SharedLibs.props" />
  </ImportGroup>
```

**Closed** 2023-01-18 13:47 UTC
Labels: bug

**Comment by mariru27** [comment] 2023-02-01 10:52
Hi @kornman00,

The fix for this problem is available in release v2023 for Clang Power Tools 

Thank you for your help, means a lot for our product

Have a nice day,
Marina

**Comment by kornman00** [comment] 2023-02-07 01:51
Thank you, Marina! I look forward to using the latest update this week 😄 !
