### ISSUE TITLE
Version 6.4 is broken for me

### ISSUE THREAD

**Issue by Philippe91** [Caphyon/clang-power-tools#888] opened 2020-10-26 15:07 UTC
Version 6.3 was fine, but version 6.4, both with LLVM 10.0 and 11.0, is broken, apparently some command line error.
E.g. I get something like:

'project_precompiled.hW:\project\source\util.cpp' file not found [clang-diagnostic-error]

Is there a way to step back to 6.3 until a fix?

Thanks

**Comment by hero101111** [comment] 2020-10-26 16:28
Hello @Philippe91 ,

Apologies about the inconvenience caused by this issue. Can you share more information about your use scenario, is this regarding the _compile_ or _tidy_ workflow? A sample project that reproduces this issue would be of help to us as well.

Regards,
Gabriel

**Comment by Philippe91** [comment] 2020-10-26 17:05
I use tidy-fix

But I could make a very small application that recreates the problem. See attached project.

More exactly, with "tidy" on the project, you get the same kind of error I get with "tidy-fix" on my project.
It seems that the usage of a precompiled header could be involved.

[ConsoleApplication2.zip](https://github.com/Caphyon/clang-power-tools/files/5440253/ConsoleApplication2.zip)

--- CLANG TIDY STARTED ---

PROJECT: W:\Temp\ConsoleApplication2\ConsoleApplication2.vcxproj
1: W:\Temp\ConsoleApplication2\ConsoleApplication2.cpp
5 errors generated.
Error while processing W:\Temp\ConsoleApplication2\ConsoleApplication2.cpp.
error: PCH file 'W:\Temp\ConsoleApplication2\ConsoleApplication2.clang.pch"W:\Temp\ConsoleApplication2\ConsoleApplication2.cpp' not found: module file not found [clang-diagnostic-error]
error: unable to read PCH file W:\Temp\ConsoleApplication2\ConsoleApplication2.clang.pch"W:\Temp\ConsoleApplication2\ConsoleApplication2.cpp: 'invalid argument' [clang-diagnostic-error]
error: unknown argument: '-checks=C:\Users\philw\AppData\Local\Temp\.clang-tidy' [clang-diagnostic-error]
error: unknown argument: '-header-filter=*.h;*.cpp' [clang-diagnostic-error]
error: unknown argument: '-quiet' [clang-diagnostic-error]

Got errors.

--- CLANG TIDY FINISHED ---

**Comment by hero101111** [comment] 2020-10-26 17:21
Thank you for the additional information, we think we've pinpointed the issue. This is appears to be caused by a problem we were already aware of and already addressed, a Clang Power Tools bugfix release is imminent.

If you need to fix it right away and can't wait until the release, you can grab the [PS script involved](https://raw.githubusercontent.com/Caphyon/clang-power-tools/master/ClangPowerTools/ClangPowerTools/clang-build.ps1) from github and place it in the Clang Power Tools VS extension directory. To locate it just search it by name in `%LOCALAPPDATA%\Microsoft\VisualStudio`.

It would be of help if you could test this manually and let us know if it addresses the issue at hand.

**Comment by Philippe91** [comment] 2020-10-26 17:50
Thanks, the new script works fine to tidy-fix :) ... but now that I can run version 6.4, I see another problem...
To separates things, I create another issue...

**Comment by hero101111** [comment] 2020-10-26 17:53
Happy to hear that. Thank you for the feedback regarding this issue.

**Comment by hero101111** [comment] 2020-10-27 12:04
Glad to let you know that Clang Power Tools v6.4.1 has been released, which includes the fix for this issue.

**Closed by hero101111** 2020-10-27 12:04 UTC
Labels: bug
