### ISSUE TITLE
clang-format works only for opened files

### ISSUE THREAD

**Issue by Alexolut** [Caphyon/clang-power-tools#590] opened 2019-04-09 13:17 UTC
Turns out that clang-format affects only opened to edit files. In particular if I do selection of entire solution and choose "Clang power tools → Clang format" via menu the only opened files will be formatted. I assumed that all of solution's files will be processed.

**Comment by hprica** [comment] 2019-05-15 07:27
Closing this issue because we already have it reported by another user. Thank you for taking the time and helping us make a better product.
https://github.com/Caphyon/clang-power-tools/issues/537

**Closed by hprica** 2019-05-15 07:27 UTC
Labels: bug

**Comment by Alexolut** [comment] 2019-05-15 08:36
Could you please clarify in what part this issue is duplicated by #537 suggested by you?

**Comment by hprica** [comment] 2019-05-15 09:10
There is a general bug when running **format** from the context menu or the toolbar when there is no open active document. We are trying to find a fix right now. 

If you want we can reopen this issue and I will move them both in Done when we are finished.

**Comment by hprica** [comment] 2019-05-28 11:28
@Alexolut the issue is resolved, and the fix will be available in this week's release.
