### ISSUE TITLE
clang-build aborts when encountering some clang errors, even when -continue is set

### ISSUE THREAD

**Issue by Arminius** [Caphyon/clang-power-tools#234] opened 2018-02-09 12:05 UTC
I don't have a full list of all errors that cause this behaviour, but as an example, I have a project whose stdafx.h contains the line
`#import "craxdrt.tlb"`

This results in the error message "Clang: #import of type library is an unsupported Microsoft feature" and aborts any further analysis.

If I run your script clang-build on my solution, then it will stop as soon as it encounters this error, even with the flag -continue. Now, it's relatively alright if this means I cannot analyze this specific project. But the script leaves most of my remaining projects unanalyzed. The fact that this one project uses a feature that clang doesn't support should not have any bearing on analysis of any other projects in my solution.

**Comment by cpp-red-lion** [comment] 2018-02-09 16:32
Hi,

Thank you for bringing this issue to our attention.
We'll investigate it and get back to you, on this thread.

**Comment by hero101111** [comment] 2018-03-19 12:34
Cannot reproduce the issue. I modified a project cpp to include a .tlb and clang compilation goes through after the _unsupported Microsoft feature_ error, given the the `-continue` switch is present.

Please upload a test project we can run further investigations.

**Comment by cpp-red-lion** [comment] 2018-03-19 13:35
I suspect the issue with `-continue` not being handled properly is related to PCH compilation.  
(eg. during PCH compilation, something included in `stdafx.h`)

**Comment by hero101111** [comment] 2018-03-19 13:44
@cpp-red-lion You're right. Managed to reproduce the issue this way.
Pushed a fix correcting behavior when encountering PCH errors while the `-continue` switch is present. 

Projects with PCH errors will be skipped, without stopping the compilation.

We'll soon release an updated version containing the fix.
Thanks for the feedback.

**Closed by hero101111** 2018-03-19 13:44 UTC
Labels: bug
