### ISSUE TITLE
Missed conditional prop sheet Imports

### ISSUE THREAD

**Issue by bjehlert** [Caphyon/clang-power-tools#686] opened 2019-09-26 01:28 UTC
In the attached files, you can see `hello_world.vcxproj` begins with these lines:

```xml
  <Import Project="$([MSBuild]::GetPathOfFileAbove('globals.props', '$(MSBuildThisFileDirectory)'))" />
  <Import Project="$(MyProjectRoot)imported_second.props" />

  <ImportGroup Label="PropertySheets">
    <Import Condition="'$(IsWindows)'=='true'" Project="$(MyProjectRoot)some_lib.props" />
  </ImportGroup>
```

The first, `globals.props`, defines `$(MyProjectRoot)`. The second, `imported_second.props` also seems to resolve correctly despite using a property defined in the prior prop sheet. I'm guessing this works correctly because the verbose output shows it being processed.

Inside `imported_second.props`, `$(IsWindows)` is conditionally set for x64. However, the verbose output does not show `some_lib.props` being processed at all and that one sets the include path needed to compile.

Therefore, if you build the attached files for x64 you will see CPT cannot find `some_lib.h` even though it compiles and runs correctly with MSBuild.

[cpt_bug_3.zip](https://github.com/Caphyon/clang-power-tools/files/3655434/cpt_bug_3.zip)

**Comment by hero101111** [comment] 2019-10-01 13:21
Hello,

This behavior is actually a duplicate of #685 , caused by early evaluation of `Platform` and `Configuration` MSBuild properties. That fix will apply to this issue as well. It will be available in the next version of Clang Power Tools (v5.3).

We really appreciate the feedback.
Regards,
Gabriel.

**Closed by hero101111** 2019-10-01 13:21 UTC
